// packages/visualization-components/src/timeline/StructureAnalysisPanel.tsx
import type { GapArea, DensityRegion, DuplicateCandidate } from '../lib/structure-analysis'

// Merkle DAG: timeline.components.structure_analysis_panel
// 構造分析結果の表示パネルコンポーネント

interface StructureAnalysisPanelProps {
  gapAreas: GapArea[]
  densityRegions: DensityRegion[]
  duplicates: DuplicateCandidate[]
  overallDensity: number
  onGapAreaClick?: (gapArea: GapArea) => void
  onDensityRegionClick?: (region: DensityRegion) => void
  onDuplicateClick?: (duplicate: DuplicateCandidate) => void
}

export default function StructureAnalysisPanel({
  gapAreas,
  densityRegions,
  duplicates,
  overallDensity,
  onGapAreaClick,
  onDensityRegionClick,
  onDuplicateClick
}: StructureAnalysisPanelProps) {
  return (
    <div className="space-y-4">
      {/* 全体密度 */}
      <div className="p-3 bg-gray-50 rounded-lg">
        <h4 className="font-semibold text-sm mb-2">全体密度</h4>
        <div className="text-xs text-gray-600">
          密度: {overallDensity.toFixed(4)}
        </div>
      </div>

      {/* 空白エリア */}
      {gapAreas.length > 0 && (
        <div className="p-3 bg-yellow-50 rounded-lg border border-yellow-200">
          <h4 className="font-semibold text-sm mb-2 flex items-center gap-2">
            <span className="text-yellow-600">?</span>
            <span>空白エリア（{gapAreas.length}箇所）</span>
          </h4>
          <p className="text-xs text-gray-600 mb-2">
            近接ノードの共通点を参考に、漏れた項目を発見できる可能性があります。
          </p>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {gapAreas.map((gap) => (
              <button
                key={gap.id}
                type="button"
                onClick={() => onGapAreaClick?.(gap)}
                className="w-full text-left p-2 bg-white rounded border border-yellow-300 hover:bg-yellow-100 transition-colors"
              >
                <div className="flex items-start justify-between mb-1">
                  <span className="text-xs font-medium text-gray-800">
                    信頼度: {(gap.confidence * 100).toFixed(0)}%
                  </span>
                  <span className="text-xs text-gray-500">
                    半径: {gap.radius.toFixed(0)}
                  </span>
                </div>
                <div className="text-xs text-gray-600 mb-1">
                  近接ノード: {gap.nearbyNodes.length}個
                </div>
                {gap.nearbyNodes.length > 0 && (
                  <div className="text-xs text-gray-500 mb-1">
                    例: {gap.nearbyNodes.slice(0, 3).map(n => n.label).join(', ')}
                  </div>
                )}
                {gap.commonEmotionProfile && (
                  <div className="text-xs text-gray-500">
                    主要感情: {Object.entries(gap.commonEmotionProfile)
                      .sort((a, b) => b[1] - a[1])
                      .slice(0, 2)
                      .map(([emotion, _]) => emotion)
                      .join(', ')}
                  </div>
                )}
                {gap.suggestedItems.length > 0 && (
                  <div className="mt-1 text-xs text-blue-600">
                    推奨: {gap.suggestedItems[0]}
                  </div>
                )}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* 密集領域 */}
      {densityRegions.filter(r => r.isOvercrowded).length > 0 && (
        <div className="p-3 bg-red-50 rounded-lg border border-red-200">
          <h4 className="font-semibold text-sm mb-2 flex items-center gap-2">
            <span className="text-red-600">⚠</span>
            <span>密集領域（{densityRegions.filter(r => r.isOvercrowded).length}箇所）</span>
          </h4>
          <p className="text-xs text-gray-600 mb-2">
            項目が密集しすぎている可能性があります。統合や分離を検討してください。
          </p>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {densityRegions
              .filter(r => r.isOvercrowded)
              .map((region) => (
                <button
                  key={region.id}
                  type="button"
                  onClick={() => onDensityRegionClick?.(region)}
                  className="w-full text-left p-2 bg-white rounded border border-red-300 hover:bg-red-100 transition-colors"
                >
                  <div className="flex items-start justify-between mb-1">
                    <span className="text-xs font-medium text-gray-800">
                      ノード数: {region.nodeCount}
                    </span>
                    <span className="text-xs text-gray-500">
                      密度: {region.density.toFixed(4)}
                    </span>
                  </div>
                  {region.suggestedSeparation && (
                    <div className="text-xs text-blue-600">
                      推奨分離距離: {region.suggestedSeparation.toFixed(0)}
                    </div>
                  )}
                  {region.nodes.length > 0 && (
                    <div className="text-xs text-gray-500 mt-1">
                      例: {region.nodes.slice(0, 3).map(n => n.label).join(', ')}
                    </div>
                  )}
                </button>
              ))}
          </div>
        </div>
      )}

      {/* 分散領域 */}
      {densityRegions.filter(r => !r.isOvercrowded).length > 0 && (
        <div className="p-3 bg-blue-50 rounded-lg border border-blue-200">
          <h4 className="font-semibold text-sm mb-2 flex items-center gap-2">
            <span className="text-blue-600">ℹ</span>
            <span>分散領域（{densityRegions.filter(r => !r.isOvercrowded).length}箇所）</span>
          </h4>
          <p className="text-xs text-gray-600 mb-2">
            項目が分散しすぎている可能性があります。関連項目の統合を検討してください。
          </p>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {densityRegions
              .filter(r => !r.isOvercrowded)
              .map((region) => (
                <button
                  key={region.id}
                  type="button"
                  onClick={() => onDensityRegionClick?.(region)}
                  className="w-full text-left p-2 bg-white rounded border border-blue-300 hover:bg-blue-100 transition-colors"
                >
                  <div className="flex items-start justify-between mb-1">
                    <span className="text-xs font-medium text-gray-800">
                      ノード数: {region.nodeCount}
                    </span>
                    <span className="text-xs text-gray-500">
                      密度: {region.density.toFixed(4)}
                    </span>
                  </div>
                  {region.nodes.length > 0 && (
                    <div className="text-xs text-gray-500 mt-1">
                      例: {region.nodes.slice(0, 3).map(n => n.label).join(', ')}
                    </div>
                  )}
                </button>
              ))}
          </div>
        </div>
      )}

      {/* 重複候補 */}
      {duplicates.length > 0 && (
        <div className="p-3 bg-orange-50 rounded-lg border border-orange-200">
          <h4 className="font-semibold text-sm mb-2 flex items-center gap-2">
            <span className="text-orange-600">🔄</span>
            <span>重複候補（{duplicates.length}組）</span>
          </h4>
          <p className="text-xs text-gray-600 mb-2">
            類似度が高い項目です。統合を検討してください。
          </p>
          <div className="space-y-2 max-h-48 overflow-y-auto">
            {duplicates.map((dup) => (
              <button
                key={dup.id}
                type="button"
                onClick={() => onDuplicateClick?.(dup)}
                className="w-full text-left p-2 bg-white rounded border border-orange-300 hover:bg-orange-100 transition-colors"
              >
                <div className="flex items-start justify-between mb-1">
                  <span className="text-xs font-medium text-gray-800">
                    {dup.labels.join(' ↔ ')}
                  </span>
                  <span className="text-xs text-gray-500">
                    {(dup.similarity * 100).toFixed(0)}%
                  </span>
                </div>
                {dup.suggestedMerge && (
                  <div className="text-xs text-blue-600 mb-1">
                    ⭐ 統合推奨
                  </div>
                )}
                {dup.commonFeatures.semanticTags.length > 0 && (
                  <div className="text-xs text-gray-500">
                    共通タグ: {dup.commonFeatures.semanticTags.slice(0, 3).join(', ')}
                  </div>
                )}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* 分析結果がない場合 */}
      {gapAreas.length === 0 && 
       densityRegions.length === 0 && 
       duplicates.length === 0 && (
        <div className="p-3 bg-gray-50 rounded-lg text-center">
          <p className="text-xs text-gray-500">
            分析結果がありません
          </p>
        </div>
      )}
    </div>
  )
}

// Merkle DAG: timeline.components.structure_analysis_panel -> implementation_complete
// 構造分析結果の表示パネルコンポーネントの実装完了

// apps/web/src/lib/components/researcher/StructureAnalysisPanel.svelte
<script lang="ts">
  import type { GapArea, DensityRegion, DuplicateCandidate, GhostPattern } from '@spirit/visualization';

  interface Props {
    gapAreas: GapArea[];
    densityRegions: DensityRegion[];
    duplicates: DuplicateCandidate[];
    ghostPatterns?: GhostPattern[];
    overallDensity: number;
    onGapAreaClick?: (gapArea: GapArea) => void;
    onDensityRegionClick?: (region: DensityRegion) => void;
    onDuplicateClick?: (duplicate: DuplicateCandidate) => void;
    onGhostPatternClick?: (pattern: GhostPattern) => void;
  }

  let {
    gapAreas,
    densityRegions,
    duplicates,
    ghostPatterns = [],
    overallDensity,
    onGapAreaClick,
    onDensityRegionClick,
    onDuplicateClick,
    onGhostPatternClick
  }: Props = $props();
</script>

<div class="space-y-6">
  <!-- 全体密度 -->
  <div class="p-4 bg-gray-50 dark:bg-gray-800/50 rounded-2xl border border-gray-100 dark:border-gray-800">
    <div class="flex items-center justify-between mb-2">
      <h4 class="font-bold text-[10px] text-gray-400 uppercase tracking-widest">Overall Density</h4>
      <span class="text-xs font-black text-gray-900 dark:text-white">{overallDensity.toFixed(4)}</span>
    </div>
    <div class="w-full bg-gray-200 dark:bg-gray-700 h-1 rounded-full overflow-hidden">
      <div class="bg-blue-500 h-full" style="width: {Math.min(100, overallDensity * 1000)}%"></div>
    </div>
  </div>

  <!-- Ghost Patterns (理論的な空間歪曲) -->
  {#if ghostPatterns.length > 0}
    <div class="space-y-3">
      <h4 class="font-bold text-[10px] text-purple-600 dark:text-purple-400 uppercase tracking-widest flex items-center gap-2">
        <span>👻</span>
        <span>Ghost Patterns ({ghostPatterns.length})</span>
      </h4>
      <div class="grid grid-cols-1 gap-2">
        {#each ghostPatterns as ghost (ghost.id)}
          <button
            type="button"
            onclick={() => onGhostPatternClick?.(ghost)}
            class="analysis-item group w-full text-left p-3 bg-white dark:bg-gray-800/40 hover:bg-purple-50 dark:hover:bg-purple-900/20 rounded-2xl border border-gray-100 dark:border-gray-800 hover:border-purple-200 dark:hover:border-purple-900/50 transition-all duration-300"
          >
            <div class="flex items-center justify-between mb-2">
              <span class="px-2 py-0.5 bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-400 text-[9px] font-black rounded-md uppercase">
                {ghost.pattern_type}
              </span>
              <span class="text-[9px] font-bold text-gray-400">Int: {(ghost.intensity * 100).toFixed(0)}%</span>
            </div>
            <div class="text-[10px] font-bold text-gray-800 dark:text-gray-200 line-clamp-2">
              {ghost.description}
            </div>
            {#if (ghost.labels ?? []).length > 0}
              <div class="mt-2 flex flex-wrap gap-1">
                {#each (ghost.labels ?? []).slice(0, 3) as label}
                  <span class="px-1.5 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-400 text-[8px] rounded">
                    {label}
                  </span>
                {/each}
              </div>
            {/if}
          </button>
        {/each}
      </div>
    </div>
  {/if}

  <!-- 空白エリア -->
  {#if gapAreas.length > 0}
    <div class="space-y-3">
      <h4 class="font-bold text-[10px] text-yellow-600 dark:text-yellow-500 uppercase tracking-widest flex items-center gap-2">
        <span>🔍</span>
        <span>Gap Discovery ({gapAreas.length})</span>
      </h4>
      <div class="grid grid-cols-1 gap-2">
        {#each gapAreas as gap (gap.id)}
          <button
            type="button"
            onclick={() => onGapAreaClick?.(gap)}
            class="analysis-item group w-full text-left p-3 bg-white dark:bg-gray-800/40 hover:bg-yellow-50 dark:hover:bg-yellow-900/20 rounded-2xl border border-gray-100 dark:border-gray-800 hover:border-yellow-200 dark:hover:border-yellow-900/50 transition-all duration-300"
          >
            <div class="flex items-center justify-between mb-2">
              <span class="px-2 py-0.5 bg-yellow-100 dark:bg-yellow-900/40 text-yellow-700 dark:text-yellow-400 text-[9px] font-black rounded-md uppercase">
                Conf: {(gap.confidence * 100).toFixed(0)}%
              </span>
              <span class="text-[9px] font-bold text-gray-400">R: {gap.radius.toFixed(0)}</span>
            </div>
            {#if (gap.suggested_items ?? gap.suggestedItems ?? []).length > 0}
              <div class="text-[10px] font-bold text-gray-800 dark:text-gray-200 line-clamp-1">
                💡 {(gap.suggested_items ?? gap.suggestedItems ?? [])[0]}
              </div>
            {/if}
            <div class="mt-2 text-[9px] text-gray-400 group-hover:text-yellow-600 transition-colors">
              {(gap.nearby_nodes ?? gap.nearbyNodes ?? []).length} nearby nodes detected
            </div>
          </button>
        {/each}
      </div>
    </div>
  {/if}

  <!-- 密集領域 -->
  {#if densityRegions.filter(r => r.is_overcrowded ?? r.isOvercrowded).length > 0}
    <div class="space-y-3">
      <h4 class="font-bold text-[10px] text-red-600 dark:text-red-500 uppercase tracking-widest flex items-center gap-2">
        <span>⚠</span>
        <span>Clusters ({densityRegions.filter(r => r.is_overcrowded ?? r.isOvercrowded).length})</span>
      </h4>
      <div class="grid grid-cols-1 gap-2">
        {#each densityRegions.filter(r => r.is_overcrowded ?? r.isOvercrowded) as region (region.id)}
          <button
            type="button"
            onclick={() => onDensityRegionClick?.(region)}
            class="analysis-item group w-full text-left p-3 bg-white dark:bg-gray-800/40 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-2xl border border-gray-100 dark:border-gray-800 hover:border-red-200 dark:hover:border-red-900/50 transition-all duration-300"
          >
            <div class="flex items-center justify-between mb-1">
              <span class="text-xs font-black text-gray-800 dark:text-gray-100">{region.node_count ?? region.nodeCount} Nodes</span>
              <span class="text-[9px] font-bold text-red-500">D: {region.density.toFixed(3)}</span>
            </div>
            <div class="text-[9px] text-gray-400">Overcrowded area detected</div>
          </button>
        {/each}
      </div>
    </div>
  {/if}

  <!-- 重複候補 -->
  {#if duplicates.length > 0}
    <div class="space-y-3">
      <h4 class="font-bold text-[10px] text-orange-600 dark:text-orange-500 uppercase tracking-widest flex items-center gap-2">
        <span>🔄</span>
        <span>Duplicate Match ({duplicates.length})</span>
      </h4>
      <div class="grid grid-cols-1 gap-2">
        {#each duplicates as dup (dup.id)}
          <button
            type="button"
            onclick={() => onDuplicateClick?.(dup)}
            class="analysis-item group w-full text-left p-3 bg-white dark:bg-gray-800/40 hover:bg-orange-50 dark:hover:bg-orange-900/20 rounded-2xl border border-gray-100 dark:border-gray-800 hover:border-orange-200 dark:hover:border-orange-900/50 transition-all duration-300"
          >
            <div class="flex items-center justify-between mb-2">
              <span class="px-2 py-0.5 bg-orange-100 dark:bg-orange-900/40 text-orange-700 dark:text-orange-400 text-[9px] font-black rounded-md uppercase">
                Sim: {(dup.similarity * 100).toFixed(0)}%
              </span>
            </div>
            <div class="text-[10px] font-bold text-gray-800 dark:text-gray-200 flex items-center gap-2">
              <span class="truncate">{dup.labels[0]}</span>
              <span class="text-gray-400">≈</span>
              <span class="truncate">{dup.labels[1]}</span>
            </div>
          </button>
        {/each}
      </div>
    </div>
  {/if}

  {#if gapAreas.length === 0 && densityRegions.length === 0 && duplicates.length === 0}
    <div class="p-12 text-center bg-gray-50/50 dark:bg-gray-800/30 rounded-3xl border border-dashed border-gray-200 dark:border-gray-800">
      <div class="text-3xl mb-3 opacity-20">🧊</div>
      <p class="text-[10px] font-bold text-gray-400 uppercase tracking-widest">No structural issues</p>
    </div>
  {/if}
</div>
