// apps/svelte-app/src/lib/jung-voice-assessment/JungVoiceTest.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { kawasakiStore } from "./store.svelte";
  import AudioVisualizer from "./AudioVisualizer.svelte";

  let { onComplete } = $props<{ onComplete?: () => void }>();

  let videoPreview: HTMLVideoElement | undefined = $state();
  let stimulusAudio: HTMLAudioElement | undefined = $state();
  
  let recognizedText = $state("");
  let isListening = $state(false);
  let wordDisplayedTime = $state(0);
  
  let recognition: any = null;
  let mediaRecorder: MediaRecorder | null = null;
  let videoChunks: Blob[] = [];
  let responseTimer: any = null;

  // Constants
  const WELCOME_MESSAGE = "ユング式言語連想検査へようこそ。これから100個の単語が表示されます。それぞれの単語から連想される言葉を、できるだけ早く声に出して回答してください。";

  onMount(async () => {
    // Initial words are loaded by parent (ParticipantView)
    // but we check just in case it's mounted directly or failed
    if (kawasakiStore.stimulusWords.length === 0) {
      await kawasakiStore.loadStimulusWords();
    }
  });

  let isInitializingMedia = false;
  // Media initialization
  async function initializeMedia() {
    if (isInitializingMedia) return;
    isInitializingMedia = true;
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        audio: true,
        video: { width: 1280, height: 720 }
      });
      kawasakiStore.stream = stream;
      kawasakiStore.deviceStatus = 'success';
      kawasakiStore.logEvent('preflight_devices_acquired');
      
      if (videoPreview) {
        videoPreview.srcObject = stream;
      }
    } catch (err: any) {
      kawasakiStore.deviceStatus = 'error';
      kawasakiStore.error = "カメラまたはマイクへのアクセスに失敗しました。";
      kawasakiStore.logEvent('preflight_devices_failed', { error: err.message });
    } finally {
      isInitializingMedia = false;
    }
  }

  // Effect to handle preflight media
  $effect(() => {
    if (kawasakiStore.testStatus === 'preflight' && !kawasakiStore.stream) {
      initializeMedia();
    }
  });

  // Effect to handle completion callback
  $effect(() => {
    if (kawasakiStore.testStatus === 'completed' && onComplete) {
      onComplete();
    }
  });

  // Recording logic
  async function startRecording(session: 1 | 2) {
    if (!kawasakiStore.stream) return;

    // Take a snapshot at the start of recording
    captureSnapshot(session);

    videoChunks = [];
    try {
      mediaRecorder = new MediaRecorder(kawasakiStore.stream, { mimeType: 'video/webm; codecs=vp9' });
      mediaRecorder.ondataavailable = (e) => {
        if (e.data.size > 0) videoChunks.push(e.data);
      };
      mediaRecorder.onstop = async () => {
        const blob = new Blob(videoChunks, { type: 'video/webm' });
        kawasakiStore.logEvent('recording_stopped', { session });
        // Upload the video
        await kawasakiStore.uploadArtifact(blob, 'video', session);
      };
      mediaRecorder.start();
      kawasakiStore.logEvent('recording_started', { session });
    } catch (e) {
      console.error("Failed to start MediaRecorder", e);
    }
  }

  function captureSnapshot(sessionIndex: number) {
    if (!videoPreview) return;

    const canvas = document.createElement('canvas');
    canvas.width = videoPreview.videoWidth;
    canvas.height = videoPreview.videoHeight;
    const ctx = canvas.getContext('2d');
    if (ctx) {
      ctx.drawImage(videoPreview, 0, 0, canvas.width, canvas.height);
      canvas.toBlob(async (blob) => {
        if (blob) {
          await kawasakiStore.uploadArtifact(blob, 'image', sessionIndex);
        }
      }, 'image/jpeg', 0.8);
    }
  }

  function stopRecording() {
    if (mediaRecorder && mediaRecorder.state === "recording") {
      mediaRecorder.stop();
    }
  }

  // Session control
  async function handleStartSession() {
    await startRecording(kawasakiStore.currentSession);
    kawasakiStore.startSession(100);
  }

  async function handleStartNextSession() {
    await startRecording(kawasakiStore.currentSession);
    kawasakiStore.startSession(100);
  }

  // Word association logic
  function startRecognition() {
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitRecognition || (window as any).webkitSpeechRecognition;
    if (!SpeechRecognition) {
      console.error("Speech Recognition not supported in this browser");
      return;
    }

    if (recognition) {
      try { recognition.stop(); } catch (e) {}
    }

    recognition = new SpeechRecognition();
    recognition.lang = 'ja-JP';
    recognition.interimResults = true;
    recognition.continuous = false;

    recognition.onstart = () => {
      isListening = true;
      kawasakiStore.logEvent('recognition_started');
    };
    recognition.onend = () => {
      isListening = false;
      kawasakiStore.logEvent('recognition_ended');
    };

    recognition.onresult = (event: any) => {
      const transcript = Array.from(event.results)
        .map((result: any) => result[0].transcript)
        .join('');
      recognizedText = transcript;
      
      if (event.results[0].isFinal) {
        handleResponse(transcript);
        recognition.stop();
      }
    };

    recognition.onerror = (event: any) => {
      console.error("Speech recognition error:", event.error);
      kawasakiStore.logEvent('recognition_error', { error: event.error });
    };

    try {
      recognition.start();
    } catch (e) {
      console.error("Failed to start recognition:", e);
    }
  }

  function handleResponse(response: string) {
    const reactionTimeMs = Date.now() - wordDisplayedTime;
    kawasakiStore.recordWordResponse({
      responseWord: response,
      reactionTimeMs
    });
    if (responseTimer) clearTimeout(responseTimer);
    recognizedText = "";
  }

  // Effect for word display
  $effect(() => {
    const isRunning = kawasakiStore.testStatus.includes('running');
    const word = kawasakiStore.stimulusWords[kawasakiStore.currentWordIndex];

    if (isRunning && word) {
      kawasakiStore.logEvent('word_displayed', { word: word.japanese, id: word.id });
      wordDisplayedTime = Date.now();
      recognizedText = "";

      // Play audio or TTS
      const audioUrl = `/audio/jung-voice-assessment/${word.id}.mp3`;
      if (stimulusAudio) {
        stimulusAudio.src = audioUrl;
        stimulusAudio.onended = () => {
          setTimeout(startRecognition, 500);
        };
        stimulusAudio.play().catch(() => {
          // Fallback to TTS
          const utterance = new SpeechSynthesisUtterance(word.japanese);
          utterance.lang = 'ja-JP';
          utterance.onend = () => setTimeout(startRecognition, 500);
          speechSynthesis.speak(utterance);
        });
      }

      // Timeout for no response (increased to 10s as per some requirements seen in other files)
      responseTimer = setTimeout(() => {
        kawasakiStore.logEvent('response_timeout', { word: word.japanese });
        if (recognition) {
          try { recognition.stop(); } catch (e) {}
        }
        kawasakiStore.advanceToNextWord();
      }, 10000);

      return () => {
        if (responseTimer) clearTimeout(responseTimer);
        if (recognition) {
          try { recognition.stop(); } catch (e) {}
        }
        speechSynthesis.cancel();
      };
    }
  });

  // Stop recording on session complete
  $effect(() => {
    if (kawasakiStore.testStatus === 'session-1-complete' || kawasakiStore.testStatus === 'completed') {
      stopRecording();
    }
  });

  onDestroy(() => {
    stopRecording();
    if (kawasakiStore.stream) {
      kawasakiStore.stream.getTracks().forEach(t => t.stop());
    }
  });
</script>

<div class="test-container">
  {#if kawasakiStore.testStatus === 'preflight'}
    <div class="screen preflight">
      <h2>デバイスチェック</h2>
      <div class="card welcome-card">
        <h3>ようこそ</h3>
        <p>{WELCOME_MESSAGE}</p>
        <button class="btn" onclick={() => stimulusAudio?.play()}>説明をもう一度聞く</button>
        <audio bind:this={stimulusAudio} src="/audio/jung-voice-assessment/welcome_message.mp3" autoPlay></audio>
      </div>

      <div class="video-container">
        <video bind:this={videoPreview} autoPlay playsInline muted class="video-preview"></video>
        {#if kawasakiStore.deviceStatus !== 'success'}
          <div class="overlay">
            <p>{kawasakiStore.deviceStatus === 'pending' ? 'カメラとマイクを準備しています...' : 'デバイスにアクセスできませんでした。'}</p>
          </div>
        {/if}
      </div>

      {#if kawasakiStore.deviceStatus === 'success'}
        <div class="status-ready">
          <p class="success-text">カメラとマイクの準備ができました。</p>
          <AudioVisualizer stream={kawasakiStore.stream} />
        </div>
      {/if}

      {#if kawasakiStore.error}
        <p class="error-text">{kawasakiStore.error}</p>
      {/if}

      <button class="btn primary large" disabled={kawasakiStore.deviceStatus !== 'success'} onclick={handleStartSession}>
        セッションを開始
      </button>
    </div>

  {:else if kawasakiStore.testStatus.includes('running')}
    <div class="screen session">
      <div class="progress-container">
        <p>セッション {kawasakiStore.currentSession} - 単語 {kawasakiStore.currentWordIndex + 1} / {kawasakiStore.stimulusWords.length}</p>
        <div class="progress-bar">
          <div class="fill" style="width: {((kawasakiStore.currentWordIndex + 1) / kawasakiStore.stimulusWords.length) * 100}%"></div>
        </div>
      </div>

      {#if kawasakiStore.stimulusWords[kawasakiStore.currentWordIndex]}
        <h1 class="stimulus-word">{kawasakiStore.stimulusWords[kawasakiStore.currentWordIndex].japanese}</h1>
      {/if}

      <div class="visualizer-box">
        <AudioVisualizer stream={kawasakiStore.stream} />
      </div>

      <div class="recognition-status">
        {#if isListening}
          <span class="listening-indicator">聞き取り中...</span>
        {/if}
        {#if recognizedText}
          <p class="recognized-text">認識結果: {recognizedText}</p>
        {/if}
      </div>
      
      <audio bind:this={stimulusAudio}></audio>
    </div>

  {:else if kawasakiStore.testStatus === 'session-1-complete'}
    <div class="screen break">
      <h2>セッション1が完了しました</h2>
      <p>短い休憩を取ってください。準備ができたら、セッション2を開始してください。</p>
      <button class="btn primary large" onclick={handleStartNextSession}>
        セッション2を開始
      </button>
    </div>

  {:else if kawasakiStore.testStatus === 'completed'}
    <div class="screen completion">
      <h2>検査完了</h2>
      <p>ご協力ありがとうございました。データは保存されました。</p>
      <button class="btn" onclick={() => kawasakiStore.resetTest()}>
        新しいセッションを開始する
      </button>
    </div>
  {/if}
</div>

<style>
  .test-container {
    width: 100%;
    max-width: 800px;
    margin: 0 auto;
  }

  .screen {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 2rem;
    padding: 2rem;
    background: white;
    border-radius: 20px;
    box-shadow: 0 10px 30px rgba(0,0,0,0.05);
  }

  .welcome-card {
    text-align: left;
    padding: 1.5rem;
    background: #f9fafb;
    border-radius: 12px;
    border: 1px solid #e5e7eb;
  }

  .video-container {
    position: relative;
    width: 100%;
    max-width: 480px;
    aspect-ratio: 16/9;
    background: #111;
    border-radius: 12px;
    overflow: hidden;
  }

  .video-preview {
    width: 100%;
    height: 100%;
    object-fit: cover;
  }

  .overlay {
    position: absolute;
    inset: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    text-align: center;
    padding: 1rem;
  }

  .stimulus-word {
    font-size: 5rem;
    font-weight: 900;
    margin: 4rem 0;
    color: #111;
  }

  .progress-container {
    width: 100%;
  }

  .progress-bar {
    width: 100%;
    height: 8px;
    background: #e5e7eb;
    border-radius: 4px;
    overflow: hidden;
    margin-top: 0.5rem;
  }

  .fill {
    height: 100%;
    background: #6366f1;
    transition: width 0.3s ease;
  }

  .success-text {
    color: #10b981;
    font-weight: 600;
  }

  .error-text {
    color: #ef4444;
  }

  .btn {
    padding: 0.75rem 1.5rem;
    border-radius: 10px;
    font-weight: 600;
    cursor: pointer;
    border: 1px solid #e5e7eb;
    background: white;
    transition: all 0.2s;
  }

  .btn.primary {
    background: #000;
    color: white;
    border: none;
  }

  .btn.large {
    padding: 1rem 3rem;
    font-size: 1.25rem;
  }

  .btn:hover:not(:disabled) {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
  }

  .btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .listening-indicator {
    color: #6366f1;
    font-weight: 600;
    animation: pulse 2s infinite;
  }

  @keyframes pulse {
    0% { opacity: 1; }
    50% { opacity: 0.5; }
    100% { opacity: 1; }
  }

  .recognized-text {
    font-size: 1.25rem;
    color: #4b5563;
    margin-top: 1rem;
  }
</style>

// v250730/src/components/jung-voice-assessment/JungVoiceTest.tsx
"use client";

import React, { useEffect, useRef, useCallback, MutableRefObject, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { useKawasakiStore } from '@/store/kawasakiStore';
import AudioVisualizer from './AudioVisualizer';
import { JUNG_TEST_WELCOME_MESSAGE } from './constants';
import type { JungVoiceTestProps } from './types';

// --- Memoized, Dumb Sub-components ---

const PreflightScreen = React.memo<{
  videoPreviewRef: MutableRefObject<HTMLVideoElement | null>;
  stream: MediaStream | null;
  deviceStatus: 'idle' | 'pending' | 'success' | 'error';
  error: string | null;
  onStartSession: () => void;
}>(({ videoPreviewRef, stream, deviceStatus, error, onStartSession }) => {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  useEffect(() => {
    if (stream && videoPreviewRef.current) {
        videoPreviewRef.current.srcObject = stream;
        videoPreviewRef.current.play().catch(e => {
            if (e.name !== 'AbortError') console.error("Video play error:", e);
        });
    }
  }, [stream, videoPreviewRef]);

  const playWelcomeAudio = () => {
    if (audioRef.current) {
      audioRef.current.play();
    }
  };

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">デバイスチェック</h2>

      <Card className="p-4">
        <CardHeader>
            <CardTitle>ようこそ</CardTitle>
        </CardHeader>
        <CardContent className="text-left">
          <p className="whitespace-pre-wrap">{JUNG_TEST_WELCOME_MESSAGE}</p>
          <audio ref={audioRef} src="/audio/jung-voice-assessment/welcome_message.mp3" autoPlay />
          <Button onClick={playWelcomeAudio} className="mt-4">
            説明をもう一度聞く
          </Button>
        </CardContent>
      </Card>

      <div className="relative w-full max-w-md mx-auto aspect-video bg-gray-900 rounded-md overflow-hidden mb-4 flex items-center justify-center">
        <video ref={videoPreviewRef} autoPlay playsInline muted className="w-full h-full object-cover"></video>
        {deviceStatus !== 'success' && (
          <div className="absolute inset-0 flex items-center justify-center text-center p-4">
            <p className="text-white/80 text-lg">
              {deviceStatus === 'pending' && 'カメラとマイクを準備しています...'}
              {deviceStatus === 'error' && 'デバイスにアクセスできませんでした。'}
            </p>
          </div>
        )}
      </div>
      {deviceStatus === 'success' && stream && (
        <div className="space-y-3 text-center">
          <p className="text-green-500">カメラとマイクの準備ができました。</p>
          <AudioVisualizer stream={stream} />
        </div>
      )}
      {error && <p className="text-red-500 mb-4">{error}</p>}
      <Button onClick={onStartSession} size="lg" disabled={!stream}>
        セッションを開始
      </Button>
    </div>
  );
});
PreflightScreen.displayName = 'PreflightScreen';


const SessionScreen = React.memo<{
  videoPreviewRef: MutableRefObject<HTMLVideoElement | null>;
  stream: MediaStream | null;
  currentSession: 1 | 2;
  currentWordIndex: number;
  stimulusWords: string[];
  onResponse: (response: string, audioBlob: Blob) => void;
}>(({ videoPreviewRef, stream, currentSession, currentWordIndex, stimulusWords, onResponse }) => {
    const [recognizedText, setRecognizedText] = useState('');
    const [isListening, setIsListening] = useState(false);
    const recognitionRef = useRef<SpeechRecognition | null>(null);
    const mediaRecorderRef = useRef<MediaRecorder | null>(null);
    const audioChunksRef = useRef<Blob[]>([]);

    useEffect(() => {
        if (stream && videoPreviewRef.current) {
            videoPreviewRef.current.srcObject = stream;
        }
    }, [stream, videoPreviewRef]);

    // Speech Synthesis and Recognition Effect
    useEffect(() => {
        if (currentWordIndex < stimulusWords.length) {
            const word = stimulusWords[currentWordIndex];
            
            // Speak the word
            const utterance = new SpeechSynthesisUtterance(word);
            speechSynthesis.speak(utterance);

            // Start listening for a response
            const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
            if (SpeechRecognition) {
                const recognition = new SpeechRecognition();
                recognition.lang = 'ja-JP';
                recognition.interimResults = true;
                recognition.continuous = false;

                recognitionRef.current = recognition;

                recognition.onstart = () => setIsListening(true);
                recognition.onend = () => setIsListening(false);

                recognition.onresult = (event) => {
                    const transcript = Array.from(event.results)
                        .map(result => result[0])
                        .map(result => result.transcript)
                        .join('');
                    setRecognizedText(transcript);

                    if (event.results[0].isFinal) {
                        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
                        onResponse(transcript, audioBlob);
                        if (recognitionRef.current) {
                            recognitionRef.current.stop();
                        }
                    }
                };

                // Media Recorder Setup
                if (stream) {
                    mediaRecorderRef.current = new MediaRecorder(stream);
                    mediaRecorderRef.current.ondataavailable = (event) => {
                        if (event.data.size > 0) {
                            audioChunksRef.current.push(event.data);
                        }
                    };
                    mediaRecorderRef.current.onstop = () => {
                        // onResponse is called when recognition is final, which should trigger stop.
                    };
                    audioChunksRef.current = [];
                    mediaRecorderRef.current.start();
                }
                
                recognition.start();
            }

            return () => {
                speechSynthesis.cancel();
                if (recognitionRef.current && isListening) {
                    recognitionRef.current.stop();
                }
                if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
                    mediaRecorderRef.current.stop();
                }
            };
        }
    }, [currentWordIndex, stimulusWords, onResponse, isListening, stream]);
  
  if (currentWordIndex >= stimulusWords.length) {
    return <div>次の単語を読み込み中...</div>;
  }

  const progress = ((currentWordIndex + 1) / stimulusWords.length) * 100;

  return (
    <div className="space-y-4 flex flex-col items-center">
      {/* <div className="relative w-40 h-32 mx-auto bg-gray-900 rounded-md overflow-hidden mb-2 flex items-center justify-center">
        <video ref={videoPreviewRef} autoPlay playsInline muted className="w-full h-full object-cover"></video>
      </div> */}
       <div className="w-full max-w-md">
          <p className="text-sm text-gray-500 mb-1">
              セッション {currentSession} - 単語 {currentWordIndex + 1} / {stimulusWords.length}
          </p>
          <div className="w-full bg-gray-200 rounded-full h-2.5">
              <div className="bg-blue-600 h-2.5 rounded-full" style={{ width: `${progress}%` }}></div>
          </div>
      </div>
      <h2 className="text-6xl font-bold my-8 h-20 flex items-center justify-center">{stimulusWords[currentWordIndex]}</h2>
      <div className="h-24 w-full max-w-md">
        {stream && <AudioVisualizer stream={stream} />}
      </div>
      <div className="h-8 text-xl text-gray-600">
        {isListening ? '聞き取り中...' : ''}
        {recognizedText && `認識結果: ${recognizedText}`}
      </div>
    </div>
  );
});
SessionScreen.displayName = 'SessionScreen';


const BreakScreen = React.memo<{ onStartNextSession: () => void; }>(({ onStartNextSession }) => (
  <div className="space-y-4">
    <h2 className="text-2xl font-bold">セッション1が完了しました</h2>
    <p>短い休憩を取ってください。準備ができたら、セッション2を開始してください。</p>
    <Button onClick={onStartNextSession} size="lg">セッション2を開始</Button>
  </div>
));
BreakScreen.displayName = 'BreakScreen';

const CompletionScreen = React.memo<{ onReset: () => void; }>(({ onReset }) => (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">検査完了</h2>
      <p>ご協力ありがとうございました。データは保存されました。</p>
      <Button onClick={onReset}>新しいセッションを開始する</Button>
    </div>
));
CompletionScreen.displayName = 'CompletionScreen';


// --- Main Component ---

export default function JungVoiceTest({
  numberOfWords = 10,
  className = '',
  onComplete,
}: JungVoiceTestProps) {
  const {
    testStatus,
    currentWordIndex,
    stimulusWords,
    startSession,
    resetTest,
    logEvent,
    saveSessionVideo,
    currentSession,
    advanceToNextWord,
    setMediaStatus,
    startPreflight,
    completeSession,
    deviceStatus,
    setDeviceStatus,
    stream,
    error,
    setStream,
    setError,
    recordWordResponse,
  } = useKawasakiStore();

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const videoPreviewRef = useRef<HTMLVideoElement | null>(null);
  const responseTimerRef = useRef<NodeJS.Timeout | null>(null);
  const wordDisplayedTimeRef = useRef<number | null>(null);
  
  // onComplete callback effect
  useEffect(() => {
    if (testStatus === 'completed' && onComplete) {
      onComplete();
    }
  }, [testStatus, onComplete]);

  // Effect for media initialization and cleanup
  useEffect(() => {
    const initializeMedia = async () => {
      setError(null);
      try {
        const mediaStream = await navigator.mediaDevices.getUserMedia({
          audio: true,
          video: { width: 1280, height: 720 }
        });
        setStream(mediaStream);
        setDeviceStatus('success');
        logEvent('preflight_devices_acquired');
      } catch (err) {
        setDeviceStatus('error');
        setError("カメラまたはマイクへのアクセスに失敗しました。ブラウザの権限設定を確認してください。");
        logEvent('preflight_devices_failed', { error: (err as Error).message });
      }
    };

    if (testStatus === 'preflight' && !stream) {
      initializeMedia();
    }
    
    // Cleanup stream when the test is fully completed or reset
    if ((testStatus === 'completed' || testStatus === 'idle') && stream) {
        stream.getTracks().forEach(track => track.stop());
        setStream(null);
    }

  }, [testStatus, stream, setDeviceStatus, logEvent, setStream, setError]);


  const stopRecording = useCallback(() => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
      mediaRecorderRef.current.stop(); // onstop will handle saving
    }
  }, []);

  const startRecording = useCallback(async (session: 1 | 2) => {
    if (!stream) {
      logEvent('recording_start_failed', { reason: 'No media stream available.' });
      setError("録画を開始できません。メディアストリームが利用できません。");
      return;
    }
  
    const videoChunks: Blob[] = [];
    try {
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm; codecs=vp9' });
      mediaRecorderRef.current = recorder;
  
      recorder.ondataavailable = (event) => {
        if (event.data.size > 0) videoChunks.push(event.data);
      };
  
      recorder.onstop = () => {
        const videoBlob = new Blob(videoChunks, { type: 'video/webm' });
        saveSessionVideo(session, videoBlob);
        logEvent('recording_stopped_and_saved', { session });
        mediaRecorderRef.current = null;
      };
  
      recorder.start();
      logEvent('recording_started', { session });
    } catch (err) {
      logEvent('media_recorder_setup_failed', { error: (err as Error).message });
      setError("MediaRecorderの作成に失敗しました。");
    }
  }, [logEvent, saveSessionVideo, stream, setError]);
  
  // Word display and advancement timer
  useEffect(() => {
    if (testStatus.includes('running') && currentWordIndex >= 0 && currentWordIndex < stimulusWords.length) {
      const word = stimulusWords[currentWordIndex];
      logEvent('word_displayed', { word });
      wordDisplayedTimeRef.current = Date.now();
      
      setMediaStatus('recording_response');
      logEvent('response_window_opened', { word });

      responseTimerRef.current = setTimeout(() => {
        logEvent('response_window_closed', { word });
        if (currentWordIndex >= stimulusWords.length - 1) {
          completeSession();
        } else {
          advanceToNextWord();
        }
      }, 6000);

      return () => {
        if (responseTimerRef.current) clearTimeout(responseTimerRef.current);
      }
    }
  }, [currentWordIndex, testStatus, stimulusWords, advanceToNextWord, logEvent, setMediaStatus, completeSession]);
  
  // Stop recording when a session or the test completes
  useEffect(() => {
    if(testStatus === 'session-1-complete' || testStatus === 'completed'){
        stopRecording();
    }
  }, [testStatus, stopRecording]);


  const handleConfirmAndStartSession = async () => {
    setError(null);
    await startRecording(1);
    startSession(numberOfWords);
  };
  
  const handleStartSecondSession = async () => {
      await startRecording(2);
      startSession(numberOfWords);
  }

  const handleResponse = (response: string, audioBlob: Blob) => {
      const reactionTimeMs = wordDisplayedTimeRef.current ? Date.now() - wordDisplayedTimeRef.current : 0;

      recordWordResponse({
          responseWord: response,
          reactionTimeMs: reactionTimeMs,
          audioBlob: audioBlob,
      });

      // The advancement logic is now in the store
      if (responseTimerRef.current) clearTimeout(responseTimerRef.current);
  };

  const renderContent = () => {
    switch (testStatus) {
      case 'preflight':
        return <PreflightScreen 
          videoPreviewRef={videoPreviewRef}
          stream={stream}
          deviceStatus={deviceStatus}
          error={error}
          onStartSession={handleConfirmAndStartSession}
        />;
      case 'session-1-running':
      case 'session-2-running':
        return <SessionScreen 
          videoPreviewRef={videoPreviewRef}
          stream={stream}
          currentSession={currentSession}
          currentWordIndex={currentWordIndex}
          stimulusWords={stimulusWords}
          onResponse={handleResponse}
        />;
      case 'session-1-complete':
        return <BreakScreen onStartNextSession={handleStartSecondSession} />;
      case 'completed':
        return <CompletionScreen onReset={resetTest} />;
      case 'idle':
      default:
        return null;
    }
  };

  return (
    <Card className={`text-center p-6 ${className}`}>
      <CardHeader>
        {/* <CardTitle>ユング式言語連想検査</CardTitle> */}
      </CardHeader>
      <CardContent>
        {error && testStatus !== 'preflight' && <p className="text-red-500 mb-4">{error}</p>}
        {renderContent()}
      </CardContent>
    </Card>
  );
}
