// apps/svelte-app/src/lib/components/ResearchPlanContent.svelte
<article class="prose prose-sm max-w-none p-4 font-sans">
  <h1 class="text-center font-bold">同意説明文書</h1>
  <h2 class="text-center text-lg">
    ユング心理学と計算モデルによるヒト錯覚の拡張的評価へのご協力についての説明文書
  </h2>
  <p class="text-center">
    <strong>2025年6月20日作成　第2.0版</strong>
  </p>

  <p>研究責任者　　新潟大学</p>
  <p>
    <u>（所属）脳研究所（氏名）田井中　一貴</u>
  </p>

  <p>本研究は倫理審査委員会にて審議され，新潟大学長の承認を得ています。</p>

  <section>
    <h2>１．研究目的及び意義</h2>
    <p>
      本研究は、「自分の手とは異なるゴムの手」に触覚を感じるという&quot;ラバーハンド実験&quot;で起こる錯覚をさらに発展させ、心理学と計算科学の技術を組み合わせて、ヒトがどのように自分の身体や心のイメージを広げて感じているのかを明らかにすることを目的としております。具体的には、ユング心理学の一手法である言語連想検査を用いて、それぞれの参加者が感じた錯覚を言語連想語と生体反応として定量化し、それをコンピュータの計算空間に変換・可視化いたします。こうして得られた情報をもとに、ヒトの心理や行動、さらには健康状態との関連をより正確にとらえることができるようになり、将来的にはメンタルヘルスの客観的評価や改善、新しい医療研究など、多方面での応用が期待されております。
    </p>
  </section>

  <section>
    <h2>２．研究協力の任意性と撤回の自由</h2>
    <p>
      この研究に参加するかどうかは，あなたの自由な意思でお決めください。参加に同意していただける場合には，同意書に署名をしていただきます。この研究への参加をお断りになることもできます。また，参加に同意していただいた場合でも，研究に参加されている期間中いつでも同意を取り消すこともできます。それらの場合に，不利益をこうむったりすることは全くありません。
    </p>
  </section>

  <section>
    <h2>３．研究方法</h2>

    <h3>３-1．研究対象者として選ばれた理由</h3>
    <p>本研究の研究対象者の条件が下記になります。</p>
    <h4>●研究に参加していただける方の主な条件</h4>
    <p>研究の趣旨を理解し同意していただいた18歳以上の健康な方を対象とします。</p>
    <h4>●研究に参加していただけない方の主な条件</h4>
    <ol>
      <li>インフォームドコンセントが得られない，あるいは本研究への辞退を表明された方</li>
      <li>研究代表者が研究参加を見送った方が良いと判断した方</li>
    </ol>

    <h3>３-2．研究方法</h3>
    <p>
      本研究は、単施設非盲検単群試験（自己対照比較試験）として行われ、健康な成人の方にご参加いただきます。本研究では、ユング心理学の言語連想検査（1910）を２セッション実施いたします。その結果をもとに、要素同士の関係性を計算科学の手法（河崎モデル）によりベクトル空間へマッピングしたのち、可視化いたします。また、言語連想法ソフトウェアを取り入れたモニターを用いて刺激実験を行い、同時に皮膚電位（SKINPRO）、画像、音声を計測・記録し、ソフトウェアを用いた感情分析も併用いたします。具体的には、被験者の方に単語が表示されるので、その単語から連想される単語を平均2秒以内に音声で回答していただきます。刺激の提示は、単語から連想する単語を通常2秒以内に発話により回答していただきます。1単語あたり最大提示時間は10秒とし、回答があった場合はそれを記録し、1秒のインターバルをとって、次の単語を提示します。合計100語を提示し、これを1セッションとします。1分の小休止の後に、もう1セッションを同様に実施し、合計2セッションの言語連想検査法を行います。実験に際しては、室温や湿度を一定範囲内に保ち、実験室内の様子をカメラで録画して外部刺激の有無を確認いたします。視覚・聴覚を通じた軽度の心理的刺激を提示する際の皮膚電位や感情の変化を記録いたします。
    </p>
    <p>
      研究実施に係る情報を取扱う際は，あなたの個人情報とは無関係の番号を付して，対応表を作成し，対応表と照合しない限り特定の個人を識別できない情報に加工を行い，あなたの秘密保護に十分配慮します。対応表は個人情報管理者が厳重に管理し，外部への提供は行いません。研究の結果を公表する際は，あなたを特定できる情報を含まないようにします。また，研究の目的以外に，研究で得られたあなたの情報を使用しません。
    </p>

    <h3>３-３．研究参加期間</h3>
    <p>
      この研究に参加された場合の予定参加期間は3時間程度を見込んでおり，場合によっては数時間程度延長させて頂きます。研究全体の予定期間は，新潟大学における人を対象とする研究等倫理審査委員会承認を受け，学長（機関の長）が実施を許可した日から2027年3月31日です。
    </p>

    <h3>３-４．研究参加予定人数</h3>
    <p>この研究は30名の方に参加をお願いする予定です。</p>

    <h3>３-５．試料・情報の保管及び廃棄</h3>
    <p>
      研究に関連する情報は，資料（文書・情報）が10年間，本学の研究責任者が責任をもって適切に保管します。情報を廃棄する場合は，個人を識別できない状態で適切に廃棄いたします。
    </p>
  </section>

  <section>
    <h2>４．研究計画書等の開示</h2>
    <p>
      詳細な研究の計画，研究の方法についてお知りになりたいときには，研究責任者までご連絡ください。この研究に参加している他の方の個人情報や，研究の知的財産等に支障がない範囲で研究計画書の閲覧や説明をいたします。
    </p>
  </section>

  <section>
    <h2>５．研究対象者にもたらされる利益，不利益</h2>
    <p>
      本研究は、心理学的な錯覚の仕組みを解明し、計算科学のモデルとして活用することを目的とした基礎研究であり、直接的な治療や健康上の利益をもたらすものではございません。実験では、視覚・聴覚的表現を使って一時的な錯覚を起こし、身体のイメージや「自分らしさ」がどのように変化するかを調べます。そのため、人によっては一時的に軽い不安や不快感を覚える場合がございますが、少しでも違和感があれば実験を休止または中止できるよう配慮しております。また、実験後には感じたことを自由にお話しいただき、研究者がフォローを行う仕組みを整えておりますので、過度の負担が生じないよう最大限注意を払っております。研究参加による直接的なメリットはございませんが、本研究で得られる知見は、将来的に心理学や医療における新たな研究や支援の可能性につながると期待されております。
    </p>
  </section>

  <section>
    <h2>６．個人情報の保護等の取扱い</h2>
    <p>
      本研究は対応表と照合しない限り特定の個人を識別できない情報に加工を行い，個人情報を保護いたします。この研究の結果が企業や学会，医学雑誌などに発表されることもあります。ただし，いずれの場合にも，あなたの個人情報（名前や住所，電話番号など）が公表されることは一切ありません。
    </p>
  </section>

  <section>
    <h2>７．試料，情報を他の機関へ提供する可能性</h2>
    <p>
      あなたから提供された検体や情報などのこの研究に関するデータは，同意を受ける時点では特定されない将来の研究のために用いる可能性があります。その場合には，別途あなたに説明した上で実施します。
    </p>
    <p>
      また，企業，他の研究機関に情報を提供する場合には，病院長に報告し，個人を特定できない形式にした上で提供します。ただし，いずれの場合にも，あなたの個人情報が公表されることは一切ありません。
    </p>
  </section>

  <section>
    <h2>８．利益相反について</h2>
    <p>
      利益相反とは，外部との経済的な利益関係等によって，研究データの改ざん，特定企業の優遇など研究が公正かつ適切に行われていないと第三者から懸念されかねない事態のことを指します。
    </p>
    <p>
      この研究は，特定の企業からの資金提供を受けておらず，特定の企業の利益を優先させて，研究の公正さを損なったりすることはありません。
    </p>
  </section>

  <section>
    <h2>９．研究に関する情報公開の方法</h2>
    <p>
      本研究の成果につきましては、学会発表や学術論文などを通じて公表する予定でございます。また、論文を発表する際には、必要に応じてプレスリリースを行い、一般の方々へ向けても広く情報をお伝えしてまいります。
    </p>
  </section>

  <section>
    <h2>11．研究により得られた結果等の取扱い</h2>
    <p>
      本研究により得られる検査結果には，一部の疾患の兆候となりえる二次的所見が得られる可能性もありますが，あなたの健康状態等を評価するための情報としては，その精度や確実性が十分ではないことから，あなたへ結果の開示は行いません。
    </p>
  </section>

  <section>
    <h2>12．研究から生じる知的財産権の帰属先</h2>
    <p>
      この研究により得られた結果が，特許権等の知的財産を生み出す可能性がありますが，その場合の特許権等は，開発・発明にかかわった研究者もしくは研究者の所属する研究機関に帰属します。そのため，本研究へあなたが研究対象者として参加することで，これらの権利が発生することはありません。
    </p>
  </section>

  <section>
    <h2>13．健康被害が発生した場合の治療と補償について</h2>
    <p>
      この研究は，心理学的なデータ収集を目的とするものであり，この研究に参加したことが直接の原因となってあなたに副作用などの健康被害が生じることは極めて稀です。万一，健康被害が生じた場合には，通常の診療と同様に，あなたにお支払いいただくこととなります。この研究による特別な補償はありません。
    </p>
  </section>

  <section>
    <h2>14．試料・情報の二次利用に関して</h2>
    <p>
      将来，この研究で得られたデータを別の研究に利用する可能性や企業，他の研究機関に提供する（二次利用）可能性があります。そのような場合も，あなたの実名を出すようなことは一切ありません。あなたの健康状態や名前などに関する情報を含め，個人情報は厳重に守ります。二次利用する場合には，改めてその研究計画を新潟大学倫理審査委員会において審査し，データ類の扱いも含め，適切な研究計画であるかどうか評価がなされて，必ず学長の承認を得て，初めて実施されます。また，二次利用の内容について新潟大学の医学部医学科ホームページの「臨床研究に関するお知らせ」にて情報を公開します。このような確認の過程を経ず，勝手に二次利用されることはありません。
    </p>
  </section>

  <section>
    <h2>15．費用負担に関する事項</h2>
    <p>
      この研究に関する経費は，研究代表者が所属する新潟大学脳研究所システム脳病態学分野田井中研究室の大学運営費・科研費および自己資金で賄われます。したがいまして，ご参加いただくにあたって，あなたの費用負担はありません。また、ご参加いただくにあたって、1時間当たり2000円の謝礼をお支払いします。なお、研究の途中で中止された場合（同意を撤回された場合）でも、それまでの参加時間に応じた謝礼をお支払いし、既にお支払いした謝礼の返金を求めることはありません。
    </p>
  </section>

  <section>
    <h2>16．お問い合わせ，苦情等の連絡先</h2>
    <p>
      この説明文書を読んでもわからないこと，研究に関する質問や何か心配事がありましたら，どうぞ遠慮なく担当者に質問してください。ご家族や友人に相談されてから研究に参加するかどうかを考えていただいても問題ありません。
    </p>
    <p>
      また，今後もし病気やけがなどで他に治療を受ける場合には，下記の担当者までご連絡をお願いします。
    </p>
    <blockquote>
      <p>所　属：新潟大学脳研究所　システム脳病態学分野（田井中研究室）</p>
      <p>住　所：新潟市中央区旭町通一番町757</p>
      <p>電話番号：０２５－２２７－０９００</p>
      <p>
        メールアドレス：
        <a href="mailto:kztainaka@bri.niigata-u.ac.jp">kztainaka@bri.niigata-u.ac.jp</a>
      </p>
      <p>
        研究責任者　<u>　（職名）　教授　　　田井中　一貴　　　　　</u>
      </p>
    </blockquote>
  </section>
</article>

<style>
  .prose {
    line-height: 1.6;
    color: #333;
  }
  h1 { font-size: 1.5rem; margin-bottom: 1rem; }
  h2 { font-size: 1.25rem; margin-top: 2rem; margin-bottom: 1rem; border-bottom: 1px solid #eee; padding-bottom: 0.5rem; }
  h3 { font-size: 1.1rem; margin-top: 1.5rem; }
  p { margin-bottom: 1rem; }
  ol { margin-bottom: 1rem; padding-left: 1.5rem; }
  blockquote {
    background: #f9f9f9;
    padding: 1rem;
    border-left: 4px solid #ccc;
    margin: 1.5rem 0;
  }
</style>

// apps/unified/src/components/participant/ResearchPlanContent.tsx
const ResearchPlanContent = () => {
  return (
    <article className="prose prose-sm dark:prose-invert max-w-none p-4 font-sans">
      <h1 className="text-center font-bold">同意説明文書</h1>
      <h2 className="text-center text-lg">
        ユング心理学と計算モデルによるヒト錯覚の拡張的評価へのご協力についての説明文書
      </h2>
      <p className="text-center">
        <strong>2025年6月20日作成　第2.0版</strong>
      </p>

      <p>研究責任者　　新潟大学</p>
      <p>
        <u>（所属）脳研究所（氏名）田井中　一貴</u>
      </p>

      <p>本研究は倫理審査委員会にて審議され，新潟大学長の承認を得ています。</p>

      <section>
        <h2>１．研究目的及び意義</h2>
        <p>
          本研究は、「自分の手とは異なるゴムの手」に触覚を感じるという&quot;ラバーハンド実験&quot;で起こる錯覚をさらに発展させ、心理学と計算科学の技術を組み合わせて、ヒトがどのように自分の身体や心のイメージを広げて感じているのかを明らかにすることを目的としております。具体的には、ユング心理学の一手法である言語連想検査を用いて、それぞれの参加者が感じた錯覚を言語連想語と生体反応として定量化し、それをコンピュータの計算空間に変換・可視化いたします。こうして得られた情報をもとに、ヒトの心理や行動、さらには健康状態との関連をより正確にとらえることができるようになり、将来的にはメンタルヘルスの客観的評価や改善、新しい医療研究など、多方面での応用が期待されております。
        </p>
      </section>

      <section>
        <h2>２．研究協力の任意性と撤回の自由</h2>
        <p>
          この研究に参加するかどうかは，あなたの自由な意思でお決めください。参加に同意していただける場合には，同意書に署名をしていただきます。この研究への参加をお断りになることもできます。また，参加に同意していただいた場合でも，研究に参加されている期間中いつでも同意を取り消すこともできます。それらの場合に，不利益をこうむったりすることは全くありません。
        </p>
      </section>

      <section>
        <h2>３．研究方法</h2>

        <h3>３-1．研究対象者として選ばれた理由</h3>
        <p>本研究の研究対象者の条件が下記になります。</p>
        <h4>●研究に参加していただける方の主な条件</h4>
        <p>研究の趣旨を理解し同意していただいた18歳以上の健康な方を対象とします。</p>
        <h4>●研究に参加していただけない方の主な条件</h4>
        <ol>
          <li>インフォームドコンセントが得られない，あるいは本研究への辞退を表明された方</li>
          <li>研究代表者が研究参加を見送った方が良いと判断した方</li>
        </ol>

        <h3>３-2．研究方法</h3>
        <p>
          本研究は、単施設非盲検単群試験（自己対照比較試験）として行われ、健康な成人の方にご参加いただきます。本研究では、ユング心理学の言語連想検査（1910）を２セッション実施いたします。その結果をもとに、要素同士の関係性を計算科学の手法（河崎モデル）によりベクトル空間へマッピングしたのち、可視化いたします。また、言語連想法ソフトウェアを取り入れたモニターを用いて刺激実験を行い、同時に皮膚電位（SKINPRO）、画像、音声を計測・記録し、ソフトウェアを用いた感情分析も併用いたします。具体的には、被験者の方に単語が表示されるので、その単語から連想される単語を平均2秒以内に音声で回答していただきます。刺激の提示は、単語から連想する単語を通常2秒以内に発話により回答していただきます。1単語あたり最大提示時間は10秒とし、回答があった場合はそれを記録し、1秒のインターバルをとって、次の単語を提示します。合計100語を提示し、これを1セッションとします。1分の小休止の後に、もう1セッションを同様に実施し、合計2セッションの言語連想検査法を行います。実験に際しては、室温や湿度を一定範囲内に保ち、実験室内の様子をカメラで録画して外部刺激の有無を確認いたします。視覚・聴覚を通じた軽度の心理的刺激を提示する際の皮膚電位や感情の変化を記録いたします。
        </p>
        <p>
          研究実施に係る情報を取扱う際は，あなたの個人情報とは無関係の番号を付して，対応表を作成し，対応表と照合しない限り特定の個人を識別できない情報に加工を行い，あなたの秘密保護に十分配慮します。対応表は個人情報管理者が厳重に管理し，外部への提供は行いません。研究の結果を公表する際は，あなたを特定できる情報を含まないようにします。また，研究の目的以外に，研究で得られたあなたの情報を使用しません。
        </p>

        <h3>３-３．研究参加期間</h3>
        <p>
          この研究に参加された場合の予定参加期間は3時間程度を見込んでおり，場合によっては数時間程度延長させて頂きます。研究全体の予定期間は，新潟大学における人を対象とする研究等倫理審査委員会承認を受け，学長（機関の長）が実施を許可した日から2027年3月31日です。
        </p>

        <h3>３-４．研究参加予定人数</h3>
        <p>この研究は30名の方に参加をお願いする予定です。</p>

        <h3>３-５．試料・情報の保管及び廃棄</h3>
        <p>
          研究に関連する情報は，資料（文書・情報）が10年間，本学の研究責任者が責任をもって適切に保管します。情報を廃棄する場合は，個人を識別できない状態で適切に廃棄いたします。
        </p>
      </section>

      <section>
        <h2>４．研究計画書等の開示</h2>
        <p>
          詳細な研究の計画，研究の方法についてお知りになりたいときには，研究責任者までご連絡ください。この研究に参加している他の方の個人情報や，研究の知的財産等に支障がない範囲で研究計画書の閲覧や説明をいたします。
        </p>
      </section>

      <section>
        <h2>５．研究対象者にもたらされる利益，不利益</h2>
        <p>
          本研究は、心理学的な錯覚の仕組みを解明し、計算科学のモデルとして活用することを目的とした基礎研究であり、直接的な治療や健康上の利益をもたらすものではございません。実験では、視覚・聴覚的表現を使って一時的な錯覚を起こし、身体のイメージや「自分らしさ」がどのように変化するかを調べます。そのため、人によっては一時的に軽い不安や不快感を覚える場合がございますが、少しでも違和感があれば実験を休止または中止できるよう配慮しております。また、実験後には感じたことを自由にお話しいただき、研究者がフォローを行う仕組みを整えておりますので、過度の負担が生じないよう最大限注意を払っております。研究参加による直接的なメリットはございませんが、本研究で得られる知見は、将来的に心理学や医療における新たな研究や支援の可能性につながると期待されております。
        </p>
      </section>

      <section>
        <h2>６．個人情報の保護等の取扱い</h2>
        <p>
          本研究は対応表と照合しない限り特定の個人を識別できない情報に加工を行い，個人情報を保護いたします。この研究の結果が企業や学会，医学雑誌などに発表されることもあります。ただし，いずれの場合にも，あなたの個人情報（名前や住所，電話番号など）が公表されることは一切ありません。
        </p>
      </section>

      <section>
        <h2>７．試料，情報を他の機関へ提供する可能性</h2>
        <p>
          あなたから提供された検体や情報などのこの研究に関するデータは，同意を受ける時点では特定されない将来の研究のために用いる可能性があります。その場合には，別途あなたに説明した上で実施します。
        </p>
        <p>
          また，企業，他の研究機関に情報を提供する場合には，病院長に報告し，個人を特定できない形式にした上で提供します。ただし，いずれの場合にも，あなたの個人情報が公表されることは一切ありません。
        </p>
      </section>

      <section>
        <h2>８．利益相反について</h2>
        <p>
          利益相反とは，外部との経済的な利益関係等によって，研究データの改ざん，特定企業の優遇など研究が公正かつ適切に行われていないと第三者から懸念されかねない事態のことを指します。
        </p>
        <p>
          この研究は，特定の企業からの資金提供を受けておらず，特定の企業の利益を優先させて，研究の公正さを損なったりすることはありません。
        </p>
      </section>

      <section>
        <h2>９．研究に関する情報公開の方法</h2>
        <p>
          本研究の成果につきましては、学会発表や学術論文などを通じて公表する予定でございます。また、論文を発表する際には、必要に応じてプレスリリースを行い、一般の方々へ向けても広く情報をお伝えしてまいります。
        </p>
      </section>

      <section>
        <h2>11．研究により得られた結果等の取扱い</h2>
        <p>
          本研究により得られる検査結果には，一部の疾患の兆候となりえる二次的所見が得られる可能性もありますが，あなたの健康状態等を評価するための情報としては，その精度や確実性が十分ではないことから，あなたへ結果の開示は行いません。
        </p>
      </section>

      <section>
        <h2>12．研究から生じる知的財産権の帰属先</h2>
        <p>
          この研究により得られた結果が，特許権等の知的財産を生み出す可能性がありますが，その場合の特許権等は，開発・発明にかかわった研究者もしくは研究者の所属する研究機関に帰属します。そのため，本研究へあなたが研究対象者として参加することで，これらの権利が発生することはありません。
        </p>
      </section>

      <section>
        <h2>13．健康被害が発生した場合の治療と補償について</h2>
        <p>
          この研究は，心理学的なデータ収集を目的とするものであり，この研究に参加したことが直接の原因となってあなたに副作用などの健康被害が生じることは極めて稀です。万一，健康被害が生じた場合には，通常の診療と同様に，あなたにお支払いいただくこととなります。この研究による特別な補償はありません。
        </p>
      </section>

      <section>
        <h2>14．試料・情報の二次利用に関して</h2>
        <p>
          将来，この研究で得られたデータを別の研究に利用する可能性や企業，他の研究機関に提供する（二次利用）可能性があります。そのような場合も，あなたの実名を出すようなことは一切ありません。あなたの健康状態や名前などに関する情報を含め，個人情報は厳重に守ります。二次利用する場合には，改めてその研究計画を新潟大学倫理審査委員会において審査し，データ類の扱いも含め，適切な研究計画であるかどうか評価がなされて，必ず学長の承認を得て，初めて実施されます。また，二次利用の内容について新潟大学の医学部医学科ホームページの「臨床研究に関するお知らせ」にて情報を公開します。このような確認の過程を経ず，勝手に二次利用されることはありません。
        </p>
      </section>

      <section>
        <h2>15．費用負担に関する事項</h2>
        <p>
          この研究に関する経費は，研究代表者が所属する新潟大学脳研究所システム脳病態学分野田井中研究室の大学運営費・科研費および自己資金で賄われます。したがいまして，ご参加いただくにあたって，あなたの費用負担はありません。また、ご参加いただくにあたって、1時間当たり2000円の謝礼をお支払いします。なお、研究の途中で中止された場合（同意を撤回された場合）でも、それまでの参加時間に応じた謝礼をお支払いし、既にお支払いした謝礼の返金を求めることはありません。
        </p>
      </section>

      <section>
        <h2>16．お問い合わせ，苦情等の連絡先</h2>
        <p>
          この説明文書を読んでもわからないこと，研究に関する質問や何か心配事がありましたら，どうぞ遠慮なく担当者に質問してください。ご家族や友人に相談されてから研究に参加するかどうかを考えていただいても問題ありません。
        </p>
        <p>
          また，今後もし病気やけがなどで他に治療を受ける場合には，下記の担当者までご連絡をお願いします。
        </p>
        <blockquote>
          <p>所　属：新潟大学脳研究所　システム脳病態学分野（田井中研究室）</p>
          <p>住　所：新潟市中央区旭町通一番町757</p>
          <p>電話番号：０２５－２２７－０９００</p>
          <p>
            メールアドレス：
            <a href="mailto:kztainaka@bri.niigata-u.ac.jp">kztainaka@bri.niigata-u.ac.jp</a>
          </p>
          <p>
            研究責任者　<u>　（職名）　教授　　　田井中　一貴　　　　　</u>
          </p>
        </blockquote>
      </section>
    </article>
  );
};

export default ResearchPlanContent;
