// apps/visualizer/src/components/Force3DWordGraphTypeGPU.tsx
'use client'

import { useRef, useEffect } from 'react'

// Merkle DAG: components.force3d_word_graph_typegpu
// TypeGPU版ユング単語連合の語ごとスケールを反映した完全グラフ3D可視化
// 依存: React, TypeGPU (WebGPU)
// BPMN: Force3DWordGraphTypeGPU

export interface WordNode {
  id: string
  label: string
  scale: number // 単語スケール（ノード半径・重み）
  axis?: [number, number, number] // 視覚方向（emotion PCA等で与える）
  fixed?: boolean
  initial?: [number, number, number]
  color?: string
}

export interface WordLink {
  source: number // インデックス（ノード配列参照）
  target: number
  weight: number // 辺スケール（太さ）
  // テンセグリティ拡張: 片側拘束の種別とパラメータ
  mode?: 'tension' | 'compression' // 省略時は従来の両側バネとして扱う
  L0?: number // 目標長さ（与えられない場合は weight から推定）
  k?: number  // 個別バネ定数（省略可）
}

interface Force3DWordGraphTypeGPUProps {
  nodes: WordNode[]
  links: WordLink[]
  width?: number
  height?: number
  background?: string
  physics?: {
    springK: number
    repulsionK: number
    damping: number
    restLength: number
    maxSpeed: number
    shellRadius?: number
    shellK?: number
    shellRadiusOuter?: number
    shellKOuter?: number
    radialOutK?: number
    constraintIters?: number
    constraintStiffness?: number
    torusR?: number
    torusr?: number
    torusK?: number
    minSep?: number
    sepK?: number
  }
  // 感情類似の影響倍率（links.weight への指数影響）
  emotionPower?: number
  // 感情場（アンカーに基づく色分布）
  emotionField?: { enabled?: boolean; radius?: number; sigma?: number; alpha?: number }
}

export default function Force3DWordGraphTypeGPU({
  nodes,
  links,
  width = 1000,
  height = 600,
  background = '#ffffff',
  physics,
  emotionPower = 1
}: Force3DWordGraphTypeGPUProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const deviceRef = useRef<GPUDevice | null>(null)
  const positionsRef = useRef<Float32Array | null>(null)
  const velocitiesRef = useRef<Float32Array | null>(null)
  const animRef = useRef<number | null>(null)
  const nodesRef = useRef<WordNode[]>(nodes)
  const linksRef = useRef<WordLink[]>(links)
  
  const physicsRef = useRef({
    springK: physics?.springK ?? 3.0,
    repulsionK: physics?.repulsionK ?? 800.0,
    damping: physics?.damping ?? 0.95,
    restLength: physics?.restLength ?? 60,
    maxSpeed: physics?.maxSpeed ?? 120,
    shellRadius: physics?.shellRadius ?? 180,
    shellK: physics?.shellK ?? 3.0,
    shellRadiusOuter: physics?.shellRadiusOuter ?? (physics?.shellRadius ? physics.shellRadius * 1.6 : 288),
    shellKOuter: physics?.shellKOuter ?? 1.5,
    radialOutK: physics?.radialOutK ?? 0,
    constraintIters: physics?.constraintIters ?? 2,
    constraintStiffness: physics?.constraintStiffness ?? 0.5,
    torusR: physics?.torusR ?? 0,
    torusr: physics?.torusr ?? 0,
    torusK: physics?.torusK ?? 0,
    minSep: physics?.minSep ?? 20,
    sepK: physics?.sepK ?? 1500,
  })

  // WebGPU 初期化
  useEffect(() => {
    if (!canvasRef.current) return

    // WebGPUデバイスを取得
    const initWebGPU = async () => {
      try {
        if (!navigator.gpu) {
          console.error('WebGPU not supported')
          return
        }

        const adapter = await navigator.gpu.requestAdapter()
        if (!adapter) {
          console.error('WebGPU adapter not available')
          return
        }
        
        const device = await adapter.requestDevice()
        deviceRef.current = device

        // 初期位置設定
        const N = nodesRef.current.length
        positionsRef.current = new Float32Array(N * 3)
        velocitiesRef.current = new Float32Array(N * 3)
        
        const pos = positionsRef.current as Float32Array
        const vel = velocitiesRef.current as Float32Array
        
        for (let i = 0; i < N; i++) {
          const init = nodesRef.current[i]?.initial
          if (init) {
            pos[i * 3] = init[0]
            pos[i * 3 + 1] = init[1]
            pos[i * 3 + 2] = init[2]
          } else {
            const theta = Math.random() * Math.PI * 2
            const phi = Math.acos(2 * Math.random() - 1)
            const r = 120 + Math.random() * 40
            pos[i * 3] = r * Math.sin(phi) * Math.cos(theta)
            pos[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta)
            pos[i * 3 + 2] = r * Math.cos(phi)
          }
          vel[i * 3] = 0
          vel[i * 3 + 1] = 0
          vel[i * 3 + 2] = 0
        }

        // WebGPUシェーダーコード
        const computeShader = `
          struct Node {
            position: vec3<f32>,
            velocity: vec3<f32>,
            scale: f32,
            fixed: u32,
          }
          
          struct Link {
            source: u32,
            target: u32,
            weight: f32,
            mode: u32,
            L0: f32,
            k: f32,
          }
          
          struct PhysicsParams {
            springK: f32,
            repulsionK: f32,
            damping: f32,
            restLength: f32,
            maxSpeed: f32,
            shellRadius: f32,
            shellK: f32,
            shellRadiusOuter: f32,
            shellKOuter: f32,
            radialOutK: f32,
            minSep: f32,
            sepK: f32,
            delta: f32,
            emotionPower: f32,
          }
          
          @group(0) @binding(0) var<storage, read_write> nodes: array<Node>;
          @group(0) @binding(1) var<storage, read> links: array<Link>;
          @group(0) @binding(2) var<uniform> params: PhysicsParams;
          
          @compute @workgroup_size(64)
          fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
            let i = global_id.x;
            if (i >= arrayLength(&nodes)) { return; }
            
            var node = nodes[i];
            if (node.fixed == 1u) { return; }
            
            var force = vec3<f32>(0.0);
            
            // Repulsion forces
            for (var j = 0u; j < arrayLength(&nodes); j++) {
              if (i == j) { continue; }
              
              let other = nodes[j];
              let dx = node.position - other.position;
              let distSq = dot(dx, dx) + 1e-6;
              let dist = sqrt(distSq);
              
              var repulsionForce = params.repulsionK / distSq;
              
              // Separation force
              if (params.minSep > 0.0 && params.sepK > 0.0 && dist < params.minSep) {
                let s = (params.minSep - dist) / max(1.0, params.minSep);
                repulsionForce += params.sepK * s * s;
              }
              
              force += (repulsionForce / dist) * dx;
            }
            
            // Spring forces
            for (var k = 0u; k < arrayLength(&links); k++) {
              let link = links[k];
              if (link.source != i && link.target != i) { continue; }
              
              let otherIndex = select(link.target, link.source, link.source == i);
              let other = nodes[otherIndex];
              
              let dx = other.position - node.position;
              let dist = length(dx) + 1e-6;
              
              let wClamped = clamp(link.weight, 0.0, 1.0);
              let wAmp = pow(wClamped, max(0.1, params.emotionPower));
              let L0guess = max(10.0, params.restLength * select(
                1.0 - 0.7 * wClamped,
                1.0 + (1.0 - wClamped) * 1.2,
                link.mode == 2u
              ));
              let L0final = select(L0guess, link.L0, link.L0 > 0.0);
              let kFinal = select(params.springK * (0.1 + 0.9 * wAmp), link.k, link.k > 0.0);
              
              var springForce = 0.0;
              let x = dist - L0final;
              
              if (link.mode == 1u) { // tension
                if (x > 0.0) { springForce = kFinal * x; }
              } else if (link.mode == 2u) { // compression
                if (x < 0.0) { springForce = kFinal * x; }
              } else { // default
                springForce = kFinal * x;
              }
              
              let sign = select(-1.0, 1.0, link.source == i);
              force += sign * (springForce / dist) * dx;
            }
            
            // Shell forces
            let rlen = length(node.position) + 1e-6;
            let radialDir = node.position / rlen;
            
            // Radial force towards shell radius
            let fr = (params.shellRadius - rlen) * params.shellK;
            force += fr * radialDir * 0.016;
            
            // Outer shell attraction
            let frOuter = (params.shellRadiusOuter - rlen) * params.shellKOuter;
            force += frOuter * radialDir * 0.016;
            
            // Radial repulsion from center
            if (params.radialOutK > 0.0) {
              let frRadial = params.radialOutK / (1.0 + rlen);
              force += frRadial * radialDir * params.delta;
            }
            
            // Update velocity
            node.velocity += force * params.delta;
            
            // Apply damping
            node.velocity *= params.damping;
            
            // Limit speed
            let speed = length(node.velocity);
            if (speed > params.maxSpeed) {
              node.velocity = normalize(node.velocity) * params.maxSpeed;
            }
            
            // Update position
            node.position += node.velocity * params.delta;
            
            nodes[i] = node;
          }
        `
        
        // コンピュートパイプラインを作成
        const computePipeline = device.createComputePipeline({
          layout: 'auto',
          compute: {
            module: device.createShaderModule({
              code: computeShader
            }),
            entryPoint: 'main'
          }
        })

        // WebGPUバッファを作成
        const nodeBuffer = device.createBuffer({
          size: nodesRef.current.length * 32, // Node struct size
          usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST | GPUBufferUsage.COPY_SRC
        })
        
        const linkBuffer = device.createBuffer({
          size: linksRef.current.length * 24, // Link struct size
          usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST
        })
        
        const paramsBuffer = device.createBuffer({
          size: 64, // PhysicsParams size
          usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST
        })
        
        // バインディンググループを作成
        const bindGroup = device.createBindGroup({
          layout: computePipeline.getBindGroupLayout(0),
          entries: [
            { binding: 0, resource: { buffer: nodeBuffer } },
            { binding: 1, resource: { buffer: linkBuffer } },
            { binding: 2, resource: { buffer: paramsBuffer } }
          ]
        })

        // アニメーションループ
        let lastTime = performance.now()
        const tick = () => {
          const now = performance.now()
          const delta = Math.min(0.05, (now - lastTime) / 1000)
          lastTime = now

          const n = nodesRef.current.length
          const l = linksRef.current.length

          if (n === 0) {
            animRef.current = requestAnimationFrame(tick)
            return
          }

          // ノードデータをWebGPUバッファに書き込み
          const nodeData = new Float32Array(n * 8) // position(3) + velocity(3) + scale(1) + fixed(1)
          for (let i = 0; i < n; i++) {
            const node = nodesRef.current[i]
            const pos = positionsRef.current
            const vel = velocitiesRef.current
            if (!pos || !vel) continue
            const ix = i * 3
            
            nodeData[i * 8] = pos[ix]
            nodeData[i * 8 + 1] = pos[ix + 1]
            nodeData[i * 8 + 2] = pos[ix + 2]
            nodeData[i * 8 + 3] = vel[ix]
            nodeData[i * 8 + 4] = vel[ix + 1]
            nodeData[i * 8 + 5] = vel[ix + 2]
            nodeData[i * 8 + 6] = node.scale
            nodeData[i * 8 + 7] = node.fixed ? 1 : 0
          }
          
          // リンクデータをWebGPUバッファに書き込み
          const linkData = new Float32Array(l * 6) // source(1) + target(1) + weight(1) + mode(1) + L0(1) + k(1)
          for (let k = 0; k < l; k++) {
            const link = linksRef.current[k]
            linkData[k * 6] = link.source
            linkData[k * 6 + 1] = link.target
            linkData[k * 6 + 2] = link.weight
            linkData[k * 6 + 3] = link.mode === 'tension' ? 1 : link.mode === 'compression' ? 2 : 0
            linkData[k * 6 + 4] = link.L0 || 0
            linkData[k * 6 + 5] = link.k || 0
          }
          
          // 物理パラメータをWebGPUバッファに書き込み
          const { springK, repulsionK, damping, restLength, maxSpeed, shellRadius, shellK, shellRadiusOuter, shellKOuter, radialOutK, minSep, sepK } = physicsRef.current
          const paramsData = new Float32Array([
            springK, repulsionK, damping, restLength, maxSpeed, shellRadius, shellK, shellRadiusOuter,
            shellKOuter, radialOutK, minSep, sepK, delta, emotionPower, 0, 0 // padding
          ])
          
          // バッファにデータを書き込み
          device.queue.writeBuffer(nodeBuffer, 0, nodeData)
          device.queue.writeBuffer(linkBuffer, 0, linkData)
          device.queue.writeBuffer(paramsBuffer, 0, paramsData)
          
          // コンピュートシェーダーを実行
          const commandEncoder = device.createCommandEncoder()
          const computePass = commandEncoder.beginComputePass()
          computePass.setPipeline(computePipeline)
          computePass.setBindGroup(0, bindGroup)
          computePass.dispatchWorkgroups(Math.ceil(n / 64))
          computePass.end()
          
          device.queue.submit([commandEncoder.finish()])
          
          // 結果を読み取り
          const readBuffer = device.createBuffer({
            size: nodeBuffer.size,
            usage: GPUBufferUsage.COPY_DST | GPUBufferUsage.MAP_READ
          })
          
          const copyEncoder = device.createCommandEncoder()
          copyEncoder.copyBufferToBuffer(nodeBuffer, 0, readBuffer, 0, nodeBuffer.size)
          device.queue.submit([copyEncoder.finish()])
          
          readBuffer.mapAsync(GPUMapMode.READ).then(() => {
            const result = new Float32Array(readBuffer.getMappedRange())
            
            // 結果を位置・速度配列に反映
            for (let i = 0; i < n; i++) {
              const node = nodesRef.current[i]
              const pos = positionsRef.current
              const vel = velocitiesRef.current
              if (!pos || !vel) continue
              const ix = i * 3
              
              if (node?.fixed && node.initial) {
                pos[ix] = node.initial[0]
                pos[ix + 1] = node.initial[1]
                pos[ix + 2] = node.initial[2]
                vel[ix] = 0
                vel[ix + 1] = 0
                vel[ix + 2] = 0
              } else {
                pos[ix] = result[i * 8]
                pos[ix + 1] = result[i * 8 + 1]
                pos[ix + 2] = result[i * 8 + 2]
                vel[ix] = result[i * 8 + 3]
                vel[ix + 1] = result[i * 8 + 4]
                vel[ix + 2] = result[i * 8 + 5]
              }
            }
            
            readBuffer.unmap()
          })

          // 2D描画（簡易版）
          const canvas = canvasRef.current
          if (canvas) {
            const ctx = canvas.getContext('2d')
            if (ctx) {
              ctx.fillStyle = background
              ctx.fillRect(0, 0, width, height)
              
              const pos = positionsRef.current
              if (!pos) return
              
              // ノード描画
              for (let i = 0; i < n; i++) {
                const ix = i * 3
                const x = pos[ix]
                const y = pos[ix + 1]
                const z = pos[ix + 2]
                
                // 3D → 2D 投影
                const scale = Math.max(0.1, 200 / (z + 200)) // 最小スケールを0.1に制限
                const screenX = width / 2 + x * scale
                const screenY = height / 2 + y * scale
                
                const node = nodesRef.current[i]
                const radius = Math.max(1, Math.min(10, 2 + node.scale)) * scale // 最小半径を1に制限
                
                ctx.beginPath()
                ctx.arc(screenX, screenY, radius, 0, Math.PI * 2)
                ctx.fillStyle = node.color || '#1e40af'
                ctx.fill()
                
                // ラベル
                ctx.fillStyle = '#1f2937'
                ctx.font = '12px sans-serif'
                ctx.textAlign = 'center'
                ctx.fillText(node.label, screenX, screenY + 4)
              }
              
              // エッジ描画
              ctx.strokeStyle = 'rgba(30, 64, 175, 0.4)'
              ctx.lineWidth = 1
              for (let k = 0; k < l; k++) {
                const link = linksRef.current[k]
                const source = link.source
                const target = link.target
                
                const sx = pos[source * 3]
                const sy = pos[source * 3 + 1]
                const sz = pos[source * 3 + 2]
                const tx = pos[target * 3]
                const ty = pos[target * 3 + 1]
                const tz = pos[target * 3 + 2]
                
                const sScale = Math.max(0.1, 200 / (sz + 200))
                const tScale = Math.max(0.1, 200 / (tz + 200))
                const sScreenX = width / 2 + sx * sScale
                const sScreenY = height / 2 + sy * sScale
                const tScreenX = width / 2 + tx * tScale
                const tScreenY = height / 2 + ty * tScale
                
                ctx.beginPath()
                ctx.moveTo(sScreenX, sScreenY)
                ctx.lineTo(tScreenX, tScreenY)
                ctx.stroke()
              }
            }
          }

          animRef.current = requestAnimationFrame(tick)
        }

        animRef.current = requestAnimationFrame(tick)

      } catch (error) {
        console.error('WebGPU initialization failed:', error)
      }
    }

    initWebGPU()

    return () => {
      if (animRef.current) cancelAnimationFrame(animRef.current)
    }
  }, [width, height, background, emotionPower])

  // 物理パラメータの差分反映
  useEffect(() => {
    physicsRef.current = {
      springK: physics?.springK ?? physicsRef.current.springK,
      repulsionK: physics?.repulsionK ?? physicsRef.current.repulsionK,
      damping: physics?.damping ?? physicsRef.current.damping,
      restLength: physics?.restLength ?? physicsRef.current.restLength,
      maxSpeed: physics?.maxSpeed ?? physicsRef.current.maxSpeed,
      shellRadius: physics?.shellRadius ?? physicsRef.current.shellRadius,
      shellK: physics?.shellK ?? physicsRef.current.shellK,
      shellRadiusOuter: physics?.shellRadiusOuter ?? physicsRef.current.shellRadiusOuter,
      shellKOuter: physics?.shellKOuter ?? physicsRef.current.shellKOuter,
      radialOutK: physics?.radialOutK ?? physicsRef.current.radialOutK,
      constraintIters: physics?.constraintIters ?? physicsRef.current.constraintIters,
      constraintStiffness: physics?.constraintStiffness ?? physicsRef.current.constraintStiffness,
      torusR: physics?.torusR ?? physicsRef.current.torusR,
      torusr: physics?.torusr ?? physicsRef.current.torusr,
      torusK: physics?.torusK ?? physicsRef.current.torusK,
      minSep: physics?.minSep ?? physicsRef.current.minSep,
      sepK: physics?.sepK ?? physicsRef.current.sepK,
    }
  }, [physics])

  // ノード・リンクの差分反映
  useEffect(() => {
    nodesRef.current = nodes
    linksRef.current = links
  }, [nodes, links])

  return (
    <div style={{ width, height, background }}>
      <canvas
        ref={canvasRef}
        width={width}
        height={height}
        style={{ width: '100%', height: '100%' }}
      />
    </div>
  )
}

// Merkle DAG: components.force3d_word_graph_typegpu -> implementation_complete

// apps/svelte-app/src/lib/components/researcher/Force3DWordGraphTypeGPU.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import type { WordNode, WordLink, GapArea, DensityRegion } from './types';

  interface Props {
    nodes: WordNode[];
    links: WordLink[];
    width?: number;
    height?: number;
    background?: string;
    maxFps?: number;
    physics?: any;
    gapAreas?: GapArea[];
    densityRegions?: DensityRegion[];
    showAnalysis?: boolean;
  }

  let {
    nodes,
    links,
    width = 1000,
    height = 600,
    background = '#ffffff',
    maxFps = 0,
    physics,
    gapAreas = [],
    densityRegions = [],
    showAnalysis = false
  }: Props = $props();

  let canvas: HTMLCanvasElement | undefined = $state();
  
  let device: any = null;
  let positions: Float32Array | null = null;
  let velocities: Float32Array | null = null;
  let animId: number | null = null;
  let connectivity: Float32Array | null = null;
  
  let nodeBuffer: any = null;
  let linkBuffer: any = null;
  let paramsBuffer: any = null;
  let bindGroup: any = null;
  let computePipeline: any = null;

  let camera = $state({
    distance: 600,
    rotationX: 0.2,
    rotationY: 0.5,
    centerX: 0,
    centerY: 0,
    centerZ: 0
  });

  let isDragging = $state(false);
  let lastMouse = { x: 0, y: 0 };

  const physicsParams = $derived({
    springK: physics?.springK ?? 2.0,
    repulsionK: physics?.repulsionK ?? 3500.0,
    damping: physics?.damping ?? 0.93,
    restLength: physics?.restLength ?? 90,
    maxSpeed: physics?.maxSpeed ?? 220,
    shellRadius: physics?.shellRadius ?? 500,
    shellK: physics?.shellK ?? 1.2,
    shellRadiusOuter: physics?.shellRadiusOuter ?? 800,
    shellKOuter: physics?.shellKOuter ?? 0.6,
    radialOutK: physics?.radialOutK ?? 120,
    constraintIters: physics?.constraintIters ?? 2,
    constraintStiffness: physics?.constraintStiffness ?? 0.5,
    minSep: physics?.minSep ?? 60,
    sepK: physics?.sepK ?? 5000,
  });

  const computeShader = `
    struct Node {
      position: vec3<f32>,
      velocity: vec3<f32>,
      scale: f32,
      fixed: u32,
    }
    
    struct Link {
      src: u32,
      dst: u32,
      weight: f32,
      mode: u32,
      L0: f32,
      k: f32,
    }
    
    struct PhysicsParams {
      springK: f32,
      repulsionK: f32,
      damping: f32,
      restLength: f32,
      maxSpeed: f32,
      shellRadius: f32,
      shellK: f32,
      shellRadiusOuter: f32,
      shellKOuter: f32,
      radialOutK: f32,
      minSep: f32,
      sepK: f32,
      delta: f32,
    }
    
    @group(0) @binding(0) var<storage, read_write> nodes: array<Node>;
    @group(0) @binding(1) var<storage, read> links: array<Link>;
    @group(0) @binding(2) var<uniform> params: PhysicsParams;
    
    @compute @workgroup_size(64)
    fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
      let i = global_id.x;
      if (i >= arrayLength(&nodes)) { return; }
      
      var node = nodes[i];
      if (node.fixed == 1u) { return; }
      
      var force = vec3<f32>(0.0);
      
      // Repulsion
      for (var j = 0u; j < arrayLength(&nodes); j++) {
        if (i == j) { continue; }
        let other = nodes[j];
        let dx = node.position - other.position;
        let distSq = dot(dx, dx) + 1e-6;
        let dist = sqrt(distSq);
        var repulsionForce = params.repulsionK / distSq;
        if (params.minSep > 0.0 && params.sepK > 0.0 && dist < params.minSep) {
          let s = (params.minSep - dist) / max(1.0, params.minSep);
          repulsionForce += params.sepK * s * s;
        }
        force += (repulsionForce / dist) * dx;
      }
      
      // Spring
      for (var k = 0u; k < arrayLength(&links); k++) {
        let link = links[k];
        if (link.src != i && link.dst != i) { continue; }
        let otherIndex = select(link.dst, link.src, link.src == i);
        let other = nodes[otherIndex];
        let dx = other.position - node.position;
        let dist = length(dx) + 1e-6;
        let wClamped = clamp(link.weight, 0.0, 1.0);
        let L0guess = params.restLength * select(1.0 - 0.7 * wClamped, 1.0 + (1.0 - wClamped) * 1.2, link.mode == 2u);
        let L0final = select(L0guess, link.L0, link.L0 > 0.0);
        let kFinal = select(params.springK * (0.1 + 0.9 * wClamped), link.k, link.k > 0.0);
        var springForce = kFinal * (dist - L0final);
        let sign = select(-1.0, 1.0, link.src == i);
        force += sign * (springForce / dist) * dx;
      }
      
      // Shell
      let rlen = length(node.position) + 1e-6;
      let radialDir = node.position / rlen;
      force += (params.shellRadius - rlen) * params.shellK * radialDir * 0.016;
      force += (params.shellRadiusOuter - rlen) * params.shellKOuter * radialDir * 0.016;
      if (params.radialOutK > 0.0) {
        force += (params.radialOutK / (1.0 + rlen)) * radialDir * params.delta;
      }
      
      node.velocity = (node.velocity + force * params.delta) * params.damping;
      if (length(node.velocity) > params.maxSpeed) {
        node.velocity = normalize(node.velocity) * params.maxSpeed;
      }
      node.position += node.velocity * params.delta;
      nodes[i] = node;
    }
  `;

  function getSpatialRGB(nodeIdx: number, positions: Float32Array): [number, number, number] {
    const node = nodes[nodeIdx];
    const hexToRgb = (hex: string): [number, number, number] => {
      const h = hex.replace('#', '');
      if (h.length === 3) return [parseInt(h[0]+h[0], 16), parseInt(h[1]+h[1], 16), parseInt(h[2]+h[2], 16)];
      return [parseInt(h.substring(0, 2), 16), parseInt(h.substring(2, 4), 16), parseInt(h.substring(4, 6), 16)];
    };

    if (node.nodeType === 'anchor') return hexToRgb(node.color || '#000000');

    const nx = positions[nodeIdx * 3];
    const ny = positions[nodeIdx * 3 + 1];
    const nz = positions[nodeIdx * 3 + 2];

    let rSum = 0, gSum = 0, bSum = 0, wSum = 0;

    nodes.forEach((anchor, ai) => {
      if (anchor.nodeType !== 'anchor' || !anchor.color) return;

      const ax = positions[ai * 3];
      const ay = positions[ai * 3 + 1];
      const az = positions[ai * 3 + 2];

      const dx = nx - ax;
      const dy = ny - ay;
      const dz = nz - az;
      const dist = Math.sqrt(dx*dx + dy*dy + dz*dz) || 1;
      const weight = 1 / Math.pow(dist / 100, 2);

      const [r, g, b] = hexToRgb(anchor.color);
      rSum += r * weight;
      gSum += g * weight;
      bSum += b * weight;
      wSum += weight;
    });

    if (wSum <= 0) return hexToRgb(node.color || '#1e40af');
    return [rSum/wSum, gSum/wSum, bSum/wSum];
  }

  function mixSpatialColor(nodeIdx: number, positions: Float32Array, alpha: number): string {
    const [r, g, b] = getSpatialRGB(nodeIdx, positions);
    return `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, ${alpha})`;
  }

  async function initWebGPU() {
    if (!(navigator as any).gpu) return;
    const adapter = await (navigator as any).gpu.requestAdapter();
    if (!adapter) return;
    device = await adapter.requestDevice();

    const shaderModule = device.createShaderModule({ code: computeShader });
    computePipeline = device.createComputePipeline({ layout: 'auto', compute: { module: shaderModule, entryPoint: 'main' } });

    positions = new Float32Array(nodes.length * 3);
    velocities = new Float32Array(nodes.length * 3);
    nodes.forEach((n, i) => {
      if (n.initial) {
        positions![i*3] = n.initial[0]; positions![i*3+1] = n.initial[1]; positions![i*3+2] = n.initial[2];
      } else {
        const r = 200 + Math.random() * 200;
        const theta = Math.random() * Math.PI * 2;
        const phi = Math.acos(2 * Math.random() - 1);
        positions![i*3] = r * Math.sin(phi) * Math.cos(theta);
        positions![i*3+1] = r * Math.sin(phi) * Math.sin(theta);
        positions![i*3+2] = r * Math.cos(phi);
      }
    });

    nodeBuffer = device.createBuffer({ size: nodes.length * 32, usage: 0x0008 | 0x0002 | 0x0004 });
    linkBuffer = device.createBuffer({ size: Math.max(links.length * 24, 24), usage: 0x0008 | 0x0002 });
    paramsBuffer = device.createBuffer({ size: 64, usage: 0x0040 | 0x0002 });

    bindGroup = device.createBindGroup({
      layout: computePipeline.getBindGroupLayout(0),
      entries: [{ binding: 0, resource: { buffer: nodeBuffer } }, { binding: 1, resource: { buffer: linkBuffer } }, { binding: 2, resource: { buffer: paramsBuffer } }]
    });

    startLoop();
  }

  function startLoop() {
    let lastTime = performance.now();
    const tick = (now: number) => {
      const delta = Math.min(0.05, (now - lastTime) / 1000);
      lastTime = now;

      if (!device || !canvas) { animId = requestAnimationFrame(tick); return; }

      const nodeData = new Float32Array(nodes.length * 8);
      nodes.forEach((n, i) => {
        nodeData[i*8] = positions![i*3]; nodeData[i*8+1] = positions![i*3+1]; nodeData[i*8+2] = positions![i*3+2];
        nodeData[i*8+3] = velocities![i*3]; nodeData[i*8+4] = velocities![i*3+1]; nodeData[i*8+5] = velocities![i*3+2];
        nodeData[i*8+6] = n.scale; nodeData[i*8+7] = n.fixed ? 1 : 0;
      });

      const linkData = new Float32Array(links.length * 6);
      links.forEach((l, i) => {
        linkData[i*6] = l.source; linkData[i*6+1] = l.target; linkData[i*6+2] = l.weight;
        linkData[i*6+3] = l.mode === 'tension' ? 1 : l.mode === 'compression' ? 2 : 0;
        linkData[i*6+4] = l.L0 || 0; linkData[i*6+5] = l.k || 0;
      });

      const paramsData = new Float32Array([
        physicsParams.springK, physicsParams.repulsionK, physicsParams.damping, physicsParams.restLength,
        physicsParams.maxSpeed, physicsParams.shellRadius, physicsParams.shellK, physicsParams.shellRadiusOuter,
        physicsParams.shellKOuter, physicsParams.radialOutK, physicsParams.minSep, physicsParams.sepK, delta, 0, 0, 0
      ]);

      device.queue.writeBuffer(nodeBuffer, 0, nodeData);
      device.queue.writeBuffer(linkBuffer, 0, linkData);
      device.queue.writeBuffer(paramsBuffer, 0, paramsData);

      const encoder = device.createCommandEncoder();
      const pass = encoder.beginComputePass();
      pass.setPipeline(computePipeline);
      pass.setBindGroup(0, bindGroup);
      pass.dispatchWorkgroups(Math.ceil(nodes.length / 64));
      pass.end();
      device.queue.submit([encoder.finish()]);

      // Simple 2D rendering for now
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.fillStyle = background; ctx.fillRect(0, 0, width, height);
        const zoom = 600 / camera.distance;

        // Pre-calculate node RGBs for current frame
        const nodeRGBs = nodes.map((_, i) => getSpatialRGB(i, positions!));

        // Links
        links.forEach(l => {
          const s = positions!.slice(l.source * 3, l.source * 3 + 3);
          const t = positions!.slice(l.target * 3, l.target * 3 + 3);
          
          if (!s || !t || s.length < 3 || t.length < 3) return;

          const project = (p: Float32Array) => {
            const x = p[0], y = p[1], z = p[2];
            const cosY = Math.cos(camera.rotationY), sinY = Math.sin(camera.rotationY);
            const rx = x * cosY - z * sinY, rz = x * sinY + z * cosY;
            const cosX = Math.cos(camera.rotationX), sinX = Math.sin(camera.rotationX);
            const cy = y * cosX - rz * sinX, cz = y * sinX + rz * cosX;
            return { x: width/2 + rx * zoom, y: height/2 + cy * zoom, z: cz };
          };

          const sp = project(s as any);
          const tp = project(t as any);

          ctx.beginPath();
          ctx.moveTo(sp.x, sp.y);
          ctx.lineTo(tp.x, tp.y);
          
          const isAnchorLink = l.mode === 'tension';
          
          // 頂点同士の色の合成（平均）
          const rgbS = nodeRGBs[l.source];
          const rgbT = nodeRGBs[l.target];
          if (rgbS && rgbT) {
            const r = (rgbS[0] + rgbT[0]) / 2;
            const g = (rgbS[1] + rgbT[1]) / 2;
            const b = (rgbS[2] + rgbT[2]) / 2;
            ctx.strokeStyle = `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, ${isAnchorLink ? 0.2 : 0.4})`;
          } else {
            ctx.strokeStyle = l.color || (isAnchorLink ? 'rgba(100, 100, 100, 0.2)' : 'rgba(30, 64, 175, 0.4)');
          }
          
          ctx.lineWidth = (isAnchorLink ? l.weight * 2 : 1) * zoom;
          ctx.stroke();
        });

        // Nodes
        nodes.forEach((n, i) => {
          const x = positions![i*3], y = positions![i*3+1], z = positions![i*3+2];
          // Simple projection
          const cosY = Math.cos(camera.rotationY), sinY = Math.sin(camera.rotationY);
          const rx = x * cosY - z * sinY, rz = x * sinY + z * cosY;
          const cosX = Math.cos(camera.rotationX), sinX = Math.sin(camera.rotationX);
          const cy = y * cosX - rz * sinX, cz = y * sinX + rz * cosX;
          const sx = width/2 + rx * zoom, sy = height/2 + cy * zoom;

          const isAnchor = n.nodeType === 'anchor';
          const radius = Math.max(1, (isAnchor ? n.scale * 1.5 : n.scale) * zoom);

          ctx.beginPath(); 
          ctx.arc(sx, sy, radius, 0, Math.PI*2);
          
          if (isAnchor) {
            // アンカーは外枠付きで描画
            ctx.fillStyle = n.color || '#000';
            ctx.globalAlpha = 0.9;
            ctx.fill();
            ctx.strokeStyle = '#fff';
            ctx.lineWidth = 2 * zoom;
            ctx.stroke();
          } else {
            const [r, g, b] = nodeRGBs[i];
            ctx.fillStyle = `rgba(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)}, 0.8)`;
            ctx.globalAlpha = 0.8;
            ctx.fill();
          }
          
          // ラベル
          ctx.globalAlpha = 1.0;
          const [r, g, b] = isAnchor ? getSpatialRGB(i, positions!) : nodeRGBs[i];
          ctx.fillStyle = `rgb(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)})`;
          ctx.font = `${isAnchor ? 'bold ' : ''}${Math.round((isAnchor ? 14 : 10) * zoom)}px sans-serif`;
          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillText(n.label, sx, sy + (isAnchor ? radius + 10 : 0));
        });
      }

      animId = requestAnimationFrame(tick);
    };
    animId = requestAnimationFrame(tick);
  }

  onMount(() => {
    initWebGPU();
  });

  onDestroy(() => {
    if (animId) cancelAnimationFrame(animId);
  });
</script>

<div class="w-full relative overflow-hidden" style="height: {height}px; background: {background};">
  <canvas
    bind:this={canvas}
    {width}
    {height}
    class="w-full h-full"
    style="cursor: {isDragging ? 'grabbing' : 'grab'}"
    onmousedown={(e) => { isDragging = true; lastMouse = { x: e.clientX, y: e.clientY }; }}
    onmousemove={(e) => {
      if (!isDragging) return;
      camera.rotationY += (e.clientX - lastMouse.x) * 0.01;
      camera.rotationX += (e.clientY - lastMouse.y) * 0.01;
      lastMouse = { x: e.clientX, y: e.clientY };
    }}
    onmouseup={() => isDragging = false}
    onwheel={(e) => {
      e.preventDefault();
      camera.distance *= e.deltaY > 0 ? 1.05 : 0.95;
    }}
  ></canvas>
</div>
