// v250730/src/components/jung-voice-assessment/JungVoiceTest.tsx
"use client";

import React, { useEffect, useRef, useCallback, MutableRefObject, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { useKawasakiStore } from '@/store/kawasakiStore';
import AudioVisualizer from './AudioVisualizer';
import { JUNG_TEST_WELCOME_MESSAGE } from './constants';
import type { JungVoiceTestProps } from './types';

// --- Memoized, Dumb Sub-components ---

const PreflightScreen = React.memo<{
  videoPreviewRef: MutableRefObject<HTMLVideoElement | null>;
  stream: MediaStream | null;
  deviceStatus: 'idle' | 'pending' | 'success' | 'error';
  error: string | null;
  onStartSession: () => void;
}>(({ videoPreviewRef, stream, deviceStatus, error, onStartSession }) => {
  const audioRef = useRef<HTMLAudioElement | null>(null);
  useEffect(() => {
    if (stream && videoPreviewRef.current) {
        videoPreviewRef.current.srcObject = stream;
        videoPreviewRef.current.play().catch(e => {
            if (e.name !== 'AbortError') console.error("Video play error:", e);
        });
    }
  }, [stream, videoPreviewRef]);

  const playWelcomeAudio = () => {
    if (audioRef.current) {
      audioRef.current.play();
    }
  };

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">デバイスチェック</h2>

      <Card className="p-4">
        <CardHeader>
            <CardTitle>ようこそ</CardTitle>
        </CardHeader>
        <CardContent className="text-left">
          <p className="whitespace-pre-wrap">{JUNG_TEST_WELCOME_MESSAGE}</p>
          <audio ref={audioRef} src="/audio/jung-voice-assessment/welcome_message.mp3" autoPlay />
          <Button onClick={playWelcomeAudio} className="mt-4">
            説明を音声で聞く
          </Button>
        </CardContent>
      </Card>

      <div className="relative w-full max-w-md mx-auto aspect-video bg-gray-900 rounded-md overflow-hidden mb-4 flex items-center justify-center">
        <video ref={videoPreviewRef} autoPlay playsInline muted className="w-full h-full object-cover"></video>
        {deviceStatus !== 'success' && (
          <div className="absolute inset-0 flex items-center justify-center text-center p-4">
            <p className="text-white/80 text-lg">
              {deviceStatus === 'pending' && 'カメラとマイクを準備しています...'}
              {deviceStatus === 'error' && 'デバイスにアクセスできませんでした。'}
            </p>
          </div>
        )}
      </div>
      {deviceStatus === 'success' && stream && (
        <div className="space-y-3 text-center">
          <p className="text-green-500">カメラとマイクの準備ができました。</p>
          <AudioVisualizer stream={stream} />
        </div>
      )}
      {error && <p className="text-red-500 mb-4">{error}</p>}
      <Button onClick={onStartSession} size="lg" disabled={!stream}>
        セッションを開始
      </Button>
    </div>
  );
});
PreflightScreen.displayName = 'PreflightScreen';


const SessionScreen = React.memo<{
  videoPreviewRef: MutableRefObject<HTMLVideoElement | null>;
  stream: MediaStream | null;
  currentSession: 1 | 2;
  currentWordIndex: number;
  stimulusWords: string[];
  onResponse: (response: string, audioBlob: Blob) => void;
}>(({ videoPreviewRef, stream, currentSession, currentWordIndex, stimulusWords, onResponse }) => {
    const [recognizedText, setRecognizedText] = useState('');
    const [isListening, setIsListening] = useState(false);
    const recognitionRef = useRef<SpeechRecognition | null>(null);
    const mediaRecorderRef = useRef<MediaRecorder | null>(null);
    const audioChunksRef = useRef<Blob[]>([]);

    useEffect(() => {
        if (stream && videoPreviewRef.current) {
            videoPreviewRef.current.srcObject = stream;
        }
    }, [stream, videoPreviewRef]);

    // Speech Synthesis and Recognition Effect
    useEffect(() => {
        if (currentWordIndex < stimulusWords.length) {
            const word = stimulusWords[currentWordIndex];
            
            // Speak the word
            const utterance = new SpeechSynthesisUtterance(word);
            speechSynthesis.speak(utterance);

            // Start listening for a response
            const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
            if (SpeechRecognition) {
                const recognition = new SpeechRecognition();
                recognition.lang = 'ja-JP';
                recognition.interimResults = true;
                recognition.continuous = false;

                recognitionRef.current = recognition;

                recognition.onstart = () => setIsListening(true);
                recognition.onend = () => setIsListening(false);

                recognition.onresult = (event) => {
                    const transcript = Array.from(event.results)
                        .map(result => result[0])
                        .map(result => result.transcript)
                        .join('');
                    setRecognizedText(transcript);

                    if (event.results[0].isFinal) {
                        const audioBlob = new Blob(audioChunksRef.current, { type: 'audio/webm' });
                        onResponse(transcript, audioBlob);
                        if (recognitionRef.current) {
                            recognitionRef.current.stop();
                        }
                    }
                };

                // Media Recorder Setup
                if (stream) {
                    mediaRecorderRef.current = new MediaRecorder(stream);
                    mediaRecorderRef.current.ondataavailable = (event) => {
                        if (event.data.size > 0) {
                            audioChunksRef.current.push(event.data);
                        }
                    };
                    mediaRecorderRef.current.onstop = () => {
                        // onResponse is called when recognition is final, which should trigger stop.
                    };
                    audioChunksRef.current = [];
                    mediaRecorderRef.current.start();
                }
                
                recognition.start();
            }

            return () => {
                speechSynthesis.cancel();
                if (recognitionRef.current && isListening) {
                    recognitionRef.current.stop();
                }
                if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
                    mediaRecorderRef.current.stop();
                }
            };
        }
    }, [currentWordIndex, stimulusWords, onResponse, isListening, stream]);
  
  if (currentWordIndex >= stimulusWords.length) {
    return <div>次の単語を読み込み中...</div>;
  }

  const progress = ((currentWordIndex + 1) / stimulusWords.length) * 100;

  return (
    <div className="space-y-4 flex flex-col items-center">
      <div className="relative w-40 h-32 mx-auto bg-gray-900 rounded-md overflow-hidden mb-2 flex items-center justify-center">
        <video ref={videoPreviewRef} autoPlay playsInline muted className="w-full h-full object-cover"></video>
      </div>
       <div className="w-full max-w-md">
          <p className="text-sm text-gray-500 mb-1">
              セッション {currentSession} - 単語 {currentWordIndex + 1} / {stimulusWords.length}
          </p>
          <div className="w-full bg-gray-200 rounded-full h-2.5">
              <div className="bg-blue-600 h-2.5 rounded-full" style={{ width: `${progress}%` }}></div>
          </div>
      </div>
      <h2 className="text-6xl font-bold my-8 h-20 flex items-center justify-center">{stimulusWords[currentWordIndex]}</h2>
      <div className="h-24 w-full max-w-md">
        {stream && <AudioVisualizer stream={stream} />}
      </div>
      <div className="h-8 text-xl text-gray-600">
        {isListening ? '聞き取り中...' : ''}
        {recognizedText && `認識結果: ${recognizedText}`}
      </div>
    </div>
  );
});
SessionScreen.displayName = 'SessionScreen';


const BreakScreen = React.memo<{ onStartNextSession: () => void; }>(({ onStartNextSession }) => (
  <div className="space-y-4">
    <h2 className="text-2xl font-bold">セッション1が完了しました</h2>
    <p>短い休憩を取ってください。準備ができたら、セッション2を開始してください。</p>
    <Button onClick={onStartNextSession} size="lg">セッション2を開始</Button>
  </div>
));
BreakScreen.displayName = 'BreakScreen';

const CompletionScreen = React.memo<{ onReset: () => void; }>(({ onReset }) => (
    <div className="space-y-4">
      <h2 className="text-2xl font-bold">検査完了</h2>
      <p>ご協力ありがとうございました。データは保存されました。</p>
      <Button onClick={onReset}>新しいセッションを開始する</Button>
    </div>
));
CompletionScreen.displayName = 'CompletionScreen';


// --- Main Component ---

export default function JungVoiceTest({
  numberOfWords = 10,
  className = '',
  onComplete,
}: JungVoiceTestProps) {
  const {
    testStatus,
    currentWordIndex,
    stimulusWords,
    startSession,
    resetTest,
    logEvent,
    saveSessionVideo,
    currentSession,
    advanceToNextWord,
    setMediaStatus,
    startPreflight,
    completeSession,
    deviceStatus,
    setDeviceStatus,
    stream,
    error,
    setStream,
    setError,
    recordWordResponse,
  } = useKawasakiStore();

  const mediaRecorderRef = useRef<MediaRecorder | null>(null);
  const videoPreviewRef = useRef<HTMLVideoElement | null>(null);
  const responseTimerRef = useRef<NodeJS.Timeout | null>(null);
  const wordDisplayedTimeRef = useRef<number | null>(null);
  
  // onComplete callback effect
  useEffect(() => {
    if (testStatus === 'completed' && onComplete) {
      onComplete();
    }
  }, [testStatus, onComplete]);

  // Effect for media initialization and cleanup
  useEffect(() => {
    const initializeMedia = async () => {
      setError(null);
      try {
        const mediaStream = await navigator.mediaDevices.getUserMedia({
          audio: true,
          video: { width: 1280, height: 720 }
        });
        setStream(mediaStream);
        setDeviceStatus('success');
        logEvent('preflight_devices_acquired');
      } catch (err) {
        setDeviceStatus('error');
        setError("カメラまたはマイクへのアクセスに失敗しました。ブラウザの権限設定を確認してください。");
        logEvent('preflight_devices_failed', { error: (err as Error).message });
      }
    };

    if (testStatus === 'preflight' && !stream) {
      initializeMedia();
    }
    
    // Cleanup stream when the test is fully completed or reset
    if ((testStatus === 'completed' || testStatus === 'idle') && stream) {
        stream.getTracks().forEach(track => track.stop());
        setStream(null);
    }

  }, [testStatus, stream, setDeviceStatus, logEvent, setStream, setError]);


  const stopRecording = useCallback(() => {
    if (mediaRecorderRef.current && mediaRecorderRef.current.state === "recording") {
      mediaRecorderRef.current.stop(); // onstop will handle saving
    }
  }, []);

  const startRecording = useCallback(async (session: 1 | 2) => {
    if (!stream) {
      logEvent('recording_start_failed', { reason: 'No media stream available.' });
      setError("録画を開始できません。メディアストリームが利用できません。");
      return;
    }
  
    const videoChunks: Blob[] = [];
    try {
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm; codecs=vp9' });
      mediaRecorderRef.current = recorder;
  
      recorder.ondataavailable = (event) => {
        if (event.data.size > 0) videoChunks.push(event.data);
      };
  
      recorder.onstop = () => {
        const videoBlob = new Blob(videoChunks, { type: 'video/webm' });
        saveSessionVideo(session, videoBlob);
        logEvent('recording_stopped_and_saved', { session });
        mediaRecorderRef.current = null;
      };
  
      recorder.start();
      logEvent('recording_started', { session });
    } catch (err) {
      logEvent('media_recorder_setup_failed', { error: (err as Error).message });
      setError("MediaRecorderの作成に失敗しました。");
    }
  }, [logEvent, saveSessionVideo, stream, setError]);
  
  // Word display and advancement timer
  useEffect(() => {
    if (testStatus.includes('running') && currentWordIndex >= 0 && currentWordIndex < stimulusWords.length) {
      const word = stimulusWords[currentWordIndex];
      logEvent('word_displayed', { word });
      wordDisplayedTimeRef.current = Date.now();
      
      setMediaStatus('recording_response');
      logEvent('response_window_opened', { word });

      responseTimerRef.current = setTimeout(() => {
        logEvent('response_window_closed', { word });
        if (currentWordIndex >= stimulusWords.length - 1) {
          completeSession();
        } else {
          advanceToNextWord();
        }
      }, 6000);

      return () => {
        if (responseTimerRef.current) clearTimeout(responseTimerRef.current);
      }
    }
  }, [currentWordIndex, testStatus, stimulusWords, advanceToNextWord, logEvent, setMediaStatus, completeSession]);
  
  // Stop recording when a session or the test completes
  useEffect(() => {
    if(testStatus === 'session-1-complete' || testStatus === 'completed'){
        stopRecording();
    }
  }, [testStatus, stopRecording]);


  const handleConfirmAndStartSession = async () => {
    setError(null);
    await startRecording(1);
    startSession(numberOfWords);
  };
  
  const handleStartSecondSession = async () => {
      await startRecording(2);
      startSession(numberOfWords);
  }

  const handleResponse = (response: string, audioBlob: Blob) => {
      const reactionTimeMs = wordDisplayedTimeRef.current ? Date.now() - wordDisplayedTimeRef.current : 0;

      recordWordResponse({
          responseWord: response,
          reactionTimeMs: reactionTimeMs,
          audioBlob: audioBlob,
      });

      // The advancement logic is now in the store
      if (responseTimerRef.current) clearTimeout(responseTimerRef.current);
  };

  const renderContent = () => {
    switch (testStatus) {
      case 'preflight':
        return <PreflightScreen 
          videoPreviewRef={videoPreviewRef}
          stream={stream}
          deviceStatus={deviceStatus}
          error={error}
          onStartSession={handleConfirmAndStartSession}
        />;
      case 'session-1-running':
      case 'session-2-running':
        return <SessionScreen 
          videoPreviewRef={videoPreviewRef}
          stream={stream}
          currentSession={currentSession}
          currentWordIndex={currentWordIndex}
          stimulusWords={stimulusWords}
          onResponse={handleResponse}
        />;
      case 'session-1-complete':
        return <BreakScreen onStartNextSession={handleStartSecondSession} />;
      case 'completed':
        return <CompletionScreen onReset={resetTest} />;
      case 'idle':
      default:
        return null;
    }
  };

  return (
    <Card className={`text-center p-6 ${className}`}>
      <CardHeader>
        <CardTitle>ユング式言語連想検査</CardTitle>
      </CardHeader>
      <CardContent>
        {error && testStatus !== 'preflight' && <p className="text-red-500 mb-4">{error}</p>}
        {renderContent()}
      </CardContent>
    </Card>
  );
}

// apps/svelte/src/lib/jung-voice-assessment/JungVoiceTest.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { kawasakiStore } from './store';
	import { get } from 'svelte/store';
	import AudioVisualizer from './AudioVisualizer.svelte';
	import SpeechRecognition from './SpeechRecognition.svelte';
	import { JUNG_TEST_WELCOME_MESSAGE } from './constants';
	import { useStimulusWords } from './hooks/useStimulusWords';
	import { useSaveSession } from './hooks/useSaveSession';
	import type { JungVoiceTestProps } from './types';

	export let numberOfWords: number = 10;
	export let onTestComplete: ((results: any) => void) | undefined = undefined;
	export let onComplete: (() => void) | undefined = undefined;
	export let graphQLCallbacks: JungVoiceTestProps['graphQLCallbacks'] = undefined;

	let videoPreview: HTMLVideoElement;
	let speechRecognition: SpeechRecognition;
	let localStream: MediaStream | null = null;
	let reactionStartTime: number | null = null;
	let currentTranscript: string = '';
	
	// Use reactive statements instead of runes for compatibility
	let store = $state(get(kawasakiStore));
	
	$effect(() => {
		const unsubscribe = kawasakiStore.subscribe((value) => {
			store = value;
		});
		return unsubscribe;
	});
	
	let testStatus = $derived(store.testStatus);
	let currentWordIndex = $derived(store.currentWordIndex);
	let stimulusWords = $derived(store.stimulusWords);
	let currentWord = $derived(stimulusWords[currentWordIndex] || null);
	let currentSession = $derived(store.currentSession);
	let deviceStatus = $derived(store.deviceStatus);
	let error = $derived(store.error);

	onMount(async () => {
		kawasakiStore.initializeParticipant();
		await loadStimulusWords();
	});

	async function loadStimulusWords() {
		const { words } = await useStimulusWords();
		if (words.length > 0) {
			kawasakiStore.setStimulusWords(words);
		}
	}

	async function startPreflight() {
		kawasakiStore.startPreflight();
		kawasakiStore.setDeviceStatus('pending');

		try {
			const mediaStream = await navigator.mediaDevices.getUserMedia({
				video: true,
				audio: true
			});
			localStream = mediaStream;
			if (videoPreview) {
				videoPreview.srcObject = mediaStream;
				await videoPreview.play();
			}
			kawasakiStore.setStream(mediaStream);
			kawasakiStore.setDeviceStatus('success');
		} catch (err) {
			console.error('Error accessing media devices:', err);
			const errorMsg = 'デバイスへのアクセスに失敗しました';
			kawasakiStore.setError(errorMsg);
			kawasakiStore.setDeviceStatus('error');
		}
	}

	function startSession() {
		kawasakiStore.startSession(numberOfWords);
		// Start showing the first word
		if (stimulusWords.length > 0) {
			showNextWord();
		}
	}

	function showNextWord() {
		if (currentWordIndex >= 0 && currentWordIndex < stimulusWords.length) {
			reactionStartTime = Date.now();
			currentTranscript = '';
			// Start speech recognition
			if (speechRecognition) {
				speechRecognition.start();
			}
		}
	}

	function handleSpeechResult(transcript: string, isFinal: boolean) {
		currentTranscript = transcript;
		
		if (isFinal && reactionStartTime) {
			const reactionTimeMs = Date.now() - reactionStartTime;
			recordResponse(transcript.trim(), reactionTimeMs);
			
			// Stop speech recognition
			if (speechRecognition) {
				speechRecognition.stop();
			}
			
			// Move to next word or complete session
			if (currentWordIndex + 1 < stimulusWords.length) {
				kawasakiStore.advanceToNextWord();
				setTimeout(() => {
					showNextWord();
				}, 1000); // 1 second pause between words
			} else {
				kawasakiStore.completeSession();
				
				// Save session data
				try {
					await useSaveSession({
						onSaveSession: graphQLCallbacks?.onSaveSession
					});
				} catch (err) {
					console.error('Failed to save session:', err);
				}
				
				if (onTestComplete) {
					const results = {
						participantId: store.participantId,
						session: currentSession,
						responses: store.wordResponses
					};
					onTestComplete(results);
				}
			}
		}
	}

	function recordResponse(responseWord: string, reactionTimeMs: number) {
		kawasakiStore.recordWordResponse({
			responseWord,
			reactionTimeMs
		});
	}
</script>

<div class="jung-voice-test">
	{#if testStatus === 'idle' || testStatus === 'preflight'}
		<div class="preflight-screen p-4">
			<h2 class="text-2xl font-bold mb-4">デバイスチェック</h2>
			<div class="bg-white dark:bg-gray-800 p-4 rounded mb-4">
				<h3 class="text-lg font-semibold mb-2">ようこそ</h3>
				<p class="whitespace-pre-wrap mb-4">{JUNG_TEST_WELCOME_MESSAGE}</p>
				<audio src="/audio/jung-voice-assessment/welcome_message.mp3" autoplay />
			</div>

			<div class="relative w-full max-w-md mx-auto aspect-video bg-gray-900 rounded-md overflow-hidden mb-4 flex items-center justify-center">
				<video bind:this={videoPreview} autoplay playsinline muted class="w-full h-full object-cover"></video>
				{#if deviceStatus !== 'success'}
					<div class="absolute inset-0 flex items-center justify-center text-white">
						<p>カメラプレビュー</p>
					</div>
				{/if}
			</div>

			{#if deviceStatus === 'success'}
				<button
					onclick={startSession}
					class="w-full bg-primary text-primary-foreground rounded-md px-4 py-2 font-semibold"
				>
					テストを開始
				</button>
			{:else}
				<button
					onclick={startPreflight}
					class="w-full bg-primary text-primary-foreground rounded-md px-4 py-2 font-semibold"
					disabled={deviceStatus === 'pending'}
				>
					{deviceStatus === 'pending' ? 'デバイスを確認中...' : 'デバイスを確認'}
				</button>
			{/if}

			{#if error}
				<div class="mt-4 p-4 bg-red-100 dark:bg-red-900 rounded text-red-800 dark:text-red-200">
					{error}
				</div>
			{/if}
		</div>
	{:else if testStatus === 'session-1-running' || testStatus === 'session-2-running'}
		<div class="test-session p-4">
			<SpeechRecognition
				bind:this={speechRecognition}
				onResult={handleSpeechResult}
				language="ja-JP"
				continuous={true}
				interimResults={true}
			/>
			<div class="mb-4">
				<AudioVisualizer stream={localStream || store.stream} />
			</div>
			{#if currentWord}
				<div class="text-center">
					<h2 class="text-4xl font-bold mb-8">{currentWord.word}</h2>
					<p class="text-gray-600 dark:text-gray-400 mb-4">
						セッション {currentSession} / 単語 {currentWordIndex + 1} / {stimulusWords.length}
					</p>
					{#if currentTranscript}
						<div class="mt-4 p-4 bg-gray-100 dark:bg-gray-700 rounded">
							<p class="text-lg">{currentTranscript}</p>
						</div>
					{/if}
				</div>
			{/if}
		</div>
	{:else if testStatus === 'completed'}
		<div class="completion-screen p-4 text-center">
			<h2 class="text-2xl font-bold mb-4">テスト完了</h2>
			<p class="mb-4">ありがとうございました。テストが完了しました。</p>
			{#if onComplete}
				<button onclick={onComplete} class="bg-primary text-primary-foreground rounded-md px-4 py-2">
					次へ
				</button>
			{/if}
		</div>
	{/if}
</div>
